################################################################################
#####                                                                      #####
#####          GGGGGGGG    TTTTTTTTTT     DDDDDDD    BBBBBBB               #####
#####         GG               TT         D     DD   B      B              #####
#####        GG    GGG         TT         D      D   BBBBBBB               #####
#####         GG     GG        TT         D     DD   B      B              #####
#####          GGGGGGG         TT         DDDDDDD    BBBBBBB               #####
#####                             CREW                                     #####
################################################################################
# Copyright (C) 2007-2012 GMDB / GTDB <http://sourceforge.net/projects/gt-db>  #
#                                                                              #
# This program is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.        #
################################################################################

#####	trinity_string	#####
## Stand: TrinityCore2 2012-04-21

## Übersetzungen für Texte 1205 bis 1224 fehlen noch!

SET NAMES 'utf8';
UPDATE trinity_string SET content_loc3=NULL;

UPDATE trinity_string SET content_loc3='Ihr solltet einen Charakter oder eine Kreatur auswählen.' WHERE entry=1;
UPDATE trinity_string SET content_loc3='Ihr solltet eine Kreatur auswählen.' WHERE entry=2;
UPDATE trinity_string SET content_loc3='[SERVER]: %s' WHERE entry=3;
UPDATE trinity_string SET content_loc3='|cffff0000[Ereignis-Nachricht]: %s|r' WHERE entry=4;
UPDATE trinity_string SET content_loc3='Es gibt keine Hilfe für diesen Befehl.' WHERE entry=5;
UPDATE trinity_string SET content_loc3='Es gibt keinen solchen Befehl.' WHERE entry=6;
UPDATE trinity_string SET content_loc3='Es gibt keinen solchen Unterbefehl.' WHERE entry=7;
UPDATE trinity_string SET content_loc3='Befehl %s hat Unterbefehle:%s' WHERE entry=8;
UPDATE trinity_string SET content_loc3='Befehle, die für Euch verfügbar sind:' WHERE entry=9;
UPDATE trinity_string SET content_loc3='Falsche Syntax.' WHERE entry=10;
UPDATE trinity_string SET content_loc3='Euer Accountlevel ist: %i' WHERE entry=11;
UPDATE trinity_string SET content_loc3='Anzahl der verbundenen Spieler: %u (Maximum: %u) Spieler in der Warteschlange: %u (Maximum: %u)' WHERE entry=12;
UPDATE trinity_string SET content_loc3='Laufzeit des Servers: %s' WHERE entry=13;
UPDATE trinity_string SET content_loc3='Spieler gespeichert.' WHERE entry=14;
UPDATE trinity_string SET content_loc3='Alle Spieler gespeichert.' WHERE entry=15;
UPDATE trinity_string SET content_loc3='Es sind derzeit folgende GMs auf diesem Server aktiv:' WHERE entry=16;
UPDATE trinity_string SET content_loc3='Zurzeit sind keine GMs auf diesem Server eingeloggt.' WHERE entry=17;
UPDATE trinity_string SET content_loc3='Dies kann nicht ausgeführt werden, während man fliegt.' WHERE entry=18;
UPDATE trinity_string SET content_loc3='Update time diff: %u..' WHERE entry=19;
UPDATE trinity_string SET content_loc3='Zeit bis zum herunterfahren/neustart: %s.' WHERE entry=20;
UPDATE trinity_string SET content_loc3='%s fliegt, Befehl fehlgeschlagen.' WHERE entry=21;
UPDATE trinity_string SET content_loc3='Ihr sitzt auf keinem Reittier, folglich könnt Ihr auch von keinem absteigen.' WHERE entry=22;
UPDATE trinity_string SET content_loc3='Kann im Kampf nicht ausgeführt werden.' WHERE entry=23;
UPDATE trinity_string SET content_loc3='Ihr habt es kürzlich verwendet.' WHERE entry=24;
UPDATE trinity_string SET content_loc3='Passwort wurde nicht geändert (unbekannter Fehler)!' WHERE entry=25;
UPDATE trinity_string SET content_loc3='Das Passwort wurde geändert.' WHERE entry=26;
UPDATE trinity_string SET content_loc3='Das alte Passwort ist falsch.' WHERE entry=27;
UPDATE trinity_string SET content_loc3='Euer Account ist nun gesperrt (Ihr könnt nur mit einer festen IP einloggen).' WHERE entry=28;
UPDATE trinity_string SET content_loc3='Euer Account ist nun entsperrt (Ihr könnt mit jeder IP einloggen).' WHERE entry=29;
UPDATE trinity_string SET content_loc3=', Rang' WHERE entry=30;
UPDATE trinity_string SET content_loc3='[bekannt]' WHERE entry=31;
UPDATE trinity_string SET content_loc3='[lernen]' WHERE entry=32;
UPDATE trinity_string SET content_loc3='[passiv]' WHERE entry=33;
UPDATE trinity_string SET content_loc3='[Talent]' WHERE entry=34;
UPDATE trinity_string SET content_loc3='[aktiv]' WHERE entry=35;
UPDATE trinity_string SET content_loc3='[komplett]' WHERE entry=36;
UPDATE trinity_string SET content_loc3='(Offline)' WHERE entry=37;
UPDATE trinity_string SET content_loc3='ein' WHERE entry=38;
UPDATE trinity_string SET content_loc3='aus' WHERE entry=39;
UPDATE trinity_string SET content_loc3='Ihr seid: %s' WHERE entry=40;
UPDATE trinity_string SET content_loc3='sichtbar' WHERE entry=41;
UPDATE trinity_string SET content_loc3='unsichtbar' WHERE entry=42;
UPDATE trinity_string SET content_loc3='Erledigt' WHERE entry=43;
UPDATE trinity_string SET content_loc3='Ihr' WHERE entry=44;
UPDATE trinity_string SET content_loc3=' <unbekannt> ' WHERE entry=45;
UPDATE trinity_string SET content_loc3='<fehler>' WHERE entry=46;
UPDATE trinity_string SET content_loc3='<Nicht existierender Charakter>' WHERE entry=47;
UPDATE trinity_string SET content_loc3='UNBEKANNT' WHERE entry=48;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %u sein, um einzutreten.' WHERE entry=49;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %u sein und Item %s besitzen, um einzutreten.' WHERE entry=50;
UPDATE trinity_string SET content_loc3='Hallo! Bereit für etwas Training?' WHERE entry=51;
UPDATE trinity_string SET content_loc3='Ungültige Itemanzahl (%u) für das Item %u' WHERE entry=52;
UPDATE trinity_string SET content_loc3='Mail kann nicht mehr als %u Itemplätze haben' WHERE entry=53;
UPDATE trinity_string SET content_loc3='Die neuen Passwörter stimmen nicht überein' WHERE entry=54;
UPDATE trinity_string SET content_loc3='Das Passwort kann nicht länger als 16 Zeichen sein (Client Limit). Das Passwort wurde nicht geändert!' WHERE entry=55;
UPDATE trinity_string SET content_loc3='Aktuelle Nachricht des Tages: \r\n%s' WHERE entry=56;
UPDATE trinity_string SET content_loc3='Verwende World-DB: %s' WHERE entry=57;
UPDATE trinity_string SET content_loc3='Verwende Script-Bibliothek: %s' WHERE entry=58;
UPDATE trinity_string SET content_loc3='Verwende creature EventAI: %s' WHERE entry=59;
UPDATE trinity_string SET content_loc3='Spieler online: %u (max %u)' WHERE entry=60;
UPDATE trinity_string SET content_loc3='Erweiterung bis %u ist jetzt verwendbar.' WHERE entry=61;
UPDATE trinity_string SET content_loc3='Mindestens ein Parameter ist falsch.' WHERE entry=62;
UPDATE trinity_string SET content_loc3='Allgemeine Ankündigung: ' WHERE entry=100;
UPDATE trinity_string SET content_loc3='Karte: %u (%s) Zone: %u (%s) Gebiet: %u (%s) Phase: %u\nX: %f Y: %f Z: %f Orientierung: %f\ngrid[%u,%u]Zelle[%u,%u] InstanzID: %u\n ZoneX: %f ZoneY: %f\nGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE entry=101;
UPDATE trinity_string SET content_loc3='%s wird bereits teleportiert.' WHERE entry=102;
UPDATE trinity_string SET content_loc3='Ihr könnt einen Spieler nur dann zu Eurer Instanz herbeiteleportieren, wenn er in Eurer Gruppe ist und Ihr der Gruppenleiter seid.' WHERE entry=103;
UPDATE trinity_string SET content_loc3='Ihr könnt nicht zur Instanz des Spielers gehen, weil Ihr in einer Gruppe seid.' WHERE entry=104;
UPDATE trinity_string SET content_loc3='Ihr könnt nur zur Instanz des Spielers gehen, während Ihr nicht in seiner Gruppe seid, wenn Euer GM-Modus angeschaltet ist.' WHERE entry=105;
UPDATE trinity_string SET content_loc3='Ihr könnt nicht zum Spieler %s gehen, da man nicht von einer Instanz in eine andere Instanz gehen kann.' WHERE entry=106;
UPDATE trinity_string SET content_loc3='Ihr könnt den Spieler %s  nicht herbeirufen, da er in einer anderen Instanz ist.' WHERE entry=107;
UPDATE trinity_string SET content_loc3='Ihr ruft %s%s herbei.' WHERE entry=108;
UPDATE trinity_string SET content_loc3='Ihr seid von %s herbeigerufen worden.' WHERE entry=109;
UPDATE trinity_string SET content_loc3='Ihr teleportiert %s%s nach %s.' WHERE entry=110;
UPDATE trinity_string SET content_loc3='Ihr seid von %s teleportiert worden.' WHERE entry=111;
UPDATE trinity_string SET content_loc3='Spieler (%s) existiert nicht.' WHERE entry=112;
UPDATE trinity_string SET content_loc3='Ihr erscheint an %s\'s Position.' WHERE entry=113;
UPDATE trinity_string SET content_loc3='%s erscheint an Eurer Position.' WHERE entry=114;
UPDATE trinity_string SET content_loc3='Falsche Werte.' WHERE entry=115;
UPDATE trinity_string SET content_loc3='Kein Charakter ausgewählt.' WHERE entry=116;
UPDATE trinity_string SET content_loc3='%s ist nicht in einer Gruppe.' WHERE entry=117;
UPDATE trinity_string SET content_loc3='Ihr verändert die HP von %s auf %i/%i.' WHERE entry=118;
UPDATE trinity_string SET content_loc3='%s hat Eure HP auf %i/%i geändert.' WHERE entry=119;
UPDATE trinity_string SET content_loc3='Ihr verändert MANA von %s auf %i/%i.' WHERE entry=120;
UPDATE trinity_string SET content_loc3='%s hat Euer MANA auf %i/%i geändert.' WHERE entry=121;
UPDATE trinity_string SET content_loc3='Ihr verändert die ENERGIE von %s auf %i/%i.' WHERE entry=122;
UPDATE trinity_string SET content_loc3='%s hat Eure ENERGIE auf %i/%i geändert.' WHERE entry=123;
UPDATE trinity_string SET content_loc3='Momentane Energie: %u' WHERE entry=124;
UPDATE trinity_string SET content_loc3='Ihr ändert die Wut von %s auf %i/%i.' WHERE entry=125;
UPDATE trinity_string SET content_loc3='%s hat Eure Wut auf %i/%i geändert.' WHERE entry=126;
UPDATE trinity_string SET content_loc3='Level von %s auf %i geändert.' WHERE entry=127;
UPDATE trinity_string SET content_loc3='GUID %i, Fraktion ist %i, flags ist %i, npcflag ist %i, DY flag ist %i' WHERE entry=128;
UPDATE trinity_string SET content_loc3='Falsche Fraktion: %u (nicht gefunden in factiontemplate.dbc).' WHERE entry=129;
UPDATE trinity_string SET content_loc3='Ihr verändert GUID=%i \'s Fraktion auf %i, flags auf %i, npcflag auf %i, dyflag auf %i.' WHERE entry=130;
UPDATE trinity_string SET content_loc3='Ihr ändert die spellflatid=%i, val= %i, mark =%i auf %s.' WHERE entry=131;
UPDATE trinity_string SET content_loc3='%s ändert Eure spellflatid=%i, val= %i, mark =%i.' WHERE entry=132;
UPDATE trinity_string SET content_loc3='%s hat nun Zugriff auf alle Flugrouten (bis er ausloggt).' WHERE entry=133;
UPDATE trinity_string SET content_loc3='%s hat nun keinen Zugriff auf alle Flugrouten mehr (nur auf bereits besuchte kann zugegriffen werden).' WHERE entry=134;
UPDATE trinity_string SET content_loc3='%s hat Euch Zugriff auf alle Flugrouten gewährt (bis Ihr ausloggt).' WHERE entry=135;
UPDATE trinity_string SET content_loc3='%s hat Euren Zugriff auf alle Flugrouten beendet (nur auf bereits besucht kann immernoch zugegriffen werden).' WHERE entry=136;
UPDATE trinity_string SET content_loc3='Ihr habt alle Geschwindigkeiten auf %2.2f vom Normalwert von %s gesetzt.' WHERE entry=137;
UPDATE trinity_string SET content_loc3='%s hat all Eure Geschwindigkeiten auf %2.2f ausgehend von normal gesetzt.' WHERE entry=138;
UPDATE trinity_string SET content_loc3='Ihr habt die Geschwindigkeit auf %2.2f vom Normalwert von %s gesetzt.' WHERE entry=139;
UPDATE trinity_string SET content_loc3='%s hat Eure Geschwindigkeit auf %2.2f ausgehend von normal gesetzt.' WHERE entry=140;
UPDATE trinity_string SET content_loc3='Ihr habt die Schwimmgeschwindigkeit auf %2.2f vom Normalwert von %s gesetzt.' WHERE entry=141;
UPDATE trinity_string SET content_loc3='%s hat Eure Schwimmgeschwindigkeit auf %2.2f ausgehend von normal gesetzt.' WHERE entry=142;
UPDATE trinity_string SET content_loc3='Ihr habt die Geschwindigkeit zum Rückwärtslaufen auf %2.2f vom Normalwert von %s gesetzt.' WHERE entry=143;
UPDATE trinity_string SET content_loc3='%s hat Eure Geschwindigkeit zum Rückwartslaufen auf %2.2f ausgehend von normal gesetzt.' WHERE entry=144;
UPDATE trinity_string SET content_loc3='Ihr habt die Fluggeschwindigkeit auf %2.2f vom Normalwert von %s gesetzt.' WHERE entry=145;
UPDATE trinity_string SET content_loc3='%s hat Eure Fluggeschwindigkeit auf %2.2f ausgehend von normal gesetzt.' WHERE entry=146;
UPDATE trinity_string SET content_loc3='Ihr habt die Größe %2.2f von %s gesetzt.' WHERE entry=147;
UPDATE trinity_string SET content_loc3='%s setzt Eure Größe auf %2.2f.' WHERE entry=148;
UPDATE trinity_string SET content_loc3='Es gibt kein solches Reittier.' WHERE entry=149;
UPDATE trinity_string SET content_loc3='Ihr gebt %s ein Reittier.' WHERE entry=150;
UPDATE trinity_string SET content_loc3='%s hat Euch ein Reittier gegeben.' WHERE entry=151;
UPDATE trinity_string SET content_loc3='USER1: %i, ADD: %i, DIF: %i\n' WHERE entry=152;
UPDATE trinity_string SET content_loc3='Ihr nehmt alles Kupfer von %s.' WHERE entry=153;
UPDATE trinity_string SET content_loc3='%s nahm Euer gesammtes Kupfer.' WHERE entry=154;
UPDATE trinity_string SET content_loc3='Ihr nehmt %i Kupfer von %s.' WHERE entry=155;
UPDATE trinity_string SET content_loc3='%s nimmt %i Kupfer von Euch.' WHERE entry=156;
UPDATE trinity_string SET content_loc3='Ihr gebt %i Kupfer zu %s.' WHERE entry=157;
UPDATE trinity_string SET content_loc3='%s gibt Euch %i Kupfer.' WHERE entry=158;
UPDATE trinity_string SET content_loc3='Ihr hört sound %u.' WHERE entry=159;
UPDATE trinity_string SET content_loc3='USER2: %i, ADD: %i, RESULT: %i\n' WHERE entry=160;
UPDATE trinity_string SET content_loc3='Entferne bit %i im Feld %i.' WHERE entry=161;
UPDATE trinity_string SET content_loc3='Setze bit %i im Feld %i.' WHERE entry=162;
UPDATE trinity_string SET content_loc3='Teleportierort-Tabelle ist leer!' WHERE entry=163;
UPDATE trinity_string SET content_loc3='Teleportierort nicht gefunden!' WHERE entry=164;
UPDATE trinity_string SET content_loc3='Benötigt Suchparameter.' WHERE entry=165;
UPDATE trinity_string SET content_loc3='Es gibt keinen Ort, der auf Eure Anfrage passt.' WHERE entry=166;
UPDATE trinity_string SET content_loc3='Gefundene Orte:\n%s' WHERE entry=168;
UPDATE trinity_string SET content_loc3='Mail an %s gesendet' WHERE entry=169;
UPDATE trinity_string SET content_loc3='Ihr versucht den Sound %u abzuspielen, dieser existiert jedoch nicht.' WHERE entry=170;
UPDATE trinity_string SET content_loc3='Ihr könnt euch nicht zu euch selber teleportieren.' WHERE entry=171;
UPDATE trinity_string SET content_loc3='Server Konsolenbefehl' WHERE entry=172;
UPDATE trinity_string SET content_loc3='Ihr ändert die Runenmacht von %s auf %i/%i.' WHERE entry=173;
UPDATE trinity_string SET content_loc3='%s ändert Eure Runenmacht auf %i/%i.' WHERE entry=174;
UPDATE trinity_string SET content_loc3='Wasserspiegel: %f, Boden: %f, Art: %u, Flags: %u, Status: %d.' WHERE entry=175;
UPDATE trinity_string SET content_loc3='Keine Auswahl.' WHERE entry=200;
UPDATE trinity_string SET content_loc3='Objekt GUID ist: lowpart %u highpart %X' WHERE entry=201;
UPDATE trinity_string SET content_loc3='Der Name war um %i Buchstaben zu lang.' WHERE entry=202;
UPDATE trinity_string SET content_loc3='Fehler, Name kann nur Buchstaben von A-Z und a-z enthalten.' WHERE entry=203;
UPDATE trinity_string SET content_loc3='Der Untername war um %i Buchstaben zu lang.' WHERE entry=204;
UPDATE trinity_string SET content_loc3='Noch nicht implementiert' WHERE entry=205;
UPDATE trinity_string SET content_loc3='Item \'%i\' \'%s\' wurde zur Liste mit einer maximal Zahl \'%i\' und incrtime \'%i\' und erweiterten Kosten \'%i\' hinzugefügt' WHERE entry=206;
UPDATE trinity_string SET content_loc3='Item \'%i\' wurde in der Datenbank nicht gefunden.' WHERE entry=207;
UPDATE trinity_string SET content_loc3='Item \'%i\' \'%s\' wurde von der Liste des Verkäufers entfernt' WHERE entry=208;
UPDATE trinity_string SET content_loc3='Item \'%i\' wurde in der Liste des Verkäufers nicht gefunden.' WHERE entry=209;
UPDATE trinity_string SET content_loc3='Item \'%u\' (mit den erweiterten Kosten %u) ist bereits in der Liste des Verkäufers.' WHERE entry=210;
UPDATE trinity_string SET content_loc3='Zauber von %s wurden zurückgesetzt.' WHERE entry=211;
UPDATE trinity_string SET content_loc3='Zauber von %s werden beim nächsten Login zurückgesetzt.' WHERE entry=212;
UPDATE trinity_string SET content_loc3='Talente von %s wurden zurückgesetzt.' WHERE entry=213;
UPDATE trinity_string SET content_loc3='Talente von %s werden beim nächsten Login zurückgesetzt.' WHERE entry=214;
UPDATE trinity_string SET content_loc3='Eure Zauber wurden zurückgesetzt.' WHERE entry=215;
UPDATE trinity_string SET content_loc3='Eure Talente wurden zurückgesetzt.' WHERE entry=216;
UPDATE trinity_string SET content_loc3='Unbekanntes Argument \'%s\' für den Befehl .resetall. Bitte vollständiges Argument mit richtiger Großschreibung eingeben.' WHERE entry=217;
UPDATE trinity_string SET content_loc3='Zauber werden für alle Spieler beim nächsten Login zurückgesetzt. Es wird dringend empfohlen sich neu einzuloggen!' WHERE entry=218;
UPDATE trinity_string SET content_loc3='Talente werden für alle Spieler beim nächsten Login zurückgesetzt. Es wird dringend empfohlen sich neu einzuloggen!' WHERE entry=219;
UPDATE trinity_string SET content_loc3='Kreatur (GUID: %u) Kein Wegpunkt gefunden.' WHERE entry=220;
UPDATE trinity_string SET content_loc3='Kreatur (GUID: %u) Letzter Wegpunkt nicht gefunden.' WHERE entry=221;
UPDATE trinity_string SET content_loc3='Kreatur (GUID: %u) Kein Wegpunkt gefunden - \'wpguid\' wurde verwendet. Versuche ihn nun durch dessen Position zu finden...' WHERE entry=222;
UPDATE trinity_string SET content_loc3='Kreatur (GUID: %u) Keine Wegpunkte gefunden - Dies ist ein Trinity-DB Problem (single float).' WHERE entry=223;
UPDATE trinity_string SET content_loc3='Angewählte Kreatur wird ignoriert - bereitgestellte GUID wird verwendet' WHERE entry=224;
UPDATE trinity_string SET content_loc3='Kreatur (GUID: %u) nicht gefunden' WHERE entry=225;
UPDATE trinity_string SET content_loc3='Ihr müsst einen visuellen Wegpunkt wählen.' WHERE entry=226;
UPDATE trinity_string SET content_loc3='Keine visuellen Wegpunkte gefunden' WHERE entry=227;
UPDATE trinity_string SET content_loc3='Konnte keinen visuellen Wegpunkt mit der creatureID: %d kreieren' WHERE entry=228;
UPDATE trinity_string SET content_loc3='Alle visuellen Wegpunkte entfernt' WHERE entry=229;
UPDATE trinity_string SET content_loc3='Konnte keine Wegpunkt-Kreatur mit der ID: %d kreieren' WHERE entry=230;
UPDATE trinity_string SET content_loc3='Keine GUID angegeben.' WHERE entry=231;
UPDATE trinity_string SET content_loc3='Keine Nummer des Wegpunktes angegeben.' WHERE entry=232;
UPDATE trinity_string SET content_loc3='Benötige Argument für \'%s\'.' WHERE entry=233;
UPDATE trinity_string SET content_loc3='Wegpunkt %i zu GUID: %d hinzugefügt.' WHERE entry=234;
UPDATE trinity_string SET content_loc3='Wegpunkt %d hinzugefügt.' WHERE entry=235;
UPDATE trinity_string SET content_loc3='Wegpunkt geändert.' WHERE entry=236;
UPDATE trinity_string SET content_loc3='Wegpunkt %s abgeändert.' WHERE entry=237;
UPDATE trinity_string SET content_loc3='Exportieren der Wegpunkte erfolgreich.' WHERE entry=238;
UPDATE trinity_string SET content_loc3='Keine Wegpunkte in der Datenbank gefunden.' WHERE entry=239;
UPDATE trinity_string SET content_loc3='Datei importiert.' WHERE entry=240;
UPDATE trinity_string SET content_loc3='Wegpunkt entfernt.' WHERE entry=241;
UPDATE trinity_string SET content_loc3='Warnung: Konnte den Wegpunkt mit der ID: %d nicht aus der Welt löschen' WHERE entry=242;
UPDATE trinity_string SET content_loc3='Das passiert, wenn der Wegpunkt von Eurem Charakter zu weit entfernt ist.' WHERE entry=243;
UPDATE trinity_string SET content_loc3='Der Wegpunkt ist aus der Datenbank gelöscht worden, aber nicht aus der Welt hier.' WHERE entry=244;
UPDATE trinity_string SET content_loc3='Sie werden nach einem Neustart des Servers verschwinden.' WHERE entry=245;
UPDATE trinity_string SET content_loc3='Wegpunkt %d: Information für Kreatur: %s, GUID: %d' WHERE entry=246;
UPDATE trinity_string SET content_loc3='Wartezeit: %d' WHERE entry=247;
UPDATE trinity_string SET content_loc3='Model %d: %d' WHERE entry=248;
UPDATE trinity_string SET content_loc3='Emote: %d' WHERE entry=249;
UPDATE trinity_string SET content_loc3='Zauber: %d' WHERE entry=250;
UPDATE trinity_string SET content_loc3='Text %d (ID: %i): %s' WHERE entry=251;
UPDATE trinity_string SET content_loc3='AIScript: %s' WHERE entry=252;
UPDATE trinity_string SET content_loc3='Spieler %s muss beim nächsten Login umbenannt werden.' WHERE entry=253;
UPDATE trinity_string SET content_loc3='Spieler %s (GUID #%u) muss beim nächsten Login umbenannt werden.' WHERE entry=254;
UPDATE trinity_string SET content_loc3='Wegpunkt-Kreatur (GUID: %u) Nicht gefunden' WHERE entry=255;
UPDATE trinity_string SET content_loc3='Konnte den NPC nicht finden...' WHERE entry=256;
UPDATE trinity_string SET content_loc3='Bewegungsart der Kreatur wurde auf \'%s\' gesetzt, Wegpunkte wurde entfernt (falls sie vorhanden waren).' WHERE entry=257;
UPDATE trinity_string SET content_loc3='Bewegungsart der Kreatur wurde auf \'%s\' gesetzt, Wegpunkte wurden nicht entfernt.' WHERE entry=258;
UPDATE trinity_string SET content_loc3='Unzulässiger Wert, benutze "on" oder "off"' WHERE entry=259;
UPDATE trinity_string SET content_loc3='Wert gespeichert.' WHERE entry=260;
UPDATE trinity_string SET content_loc3='Wert gespeichert, es kann sein, dass Ihr neu einloggen oder Euren Client-Cache leeren müsst.' WHERE entry=261;
UPDATE trinity_string SET content_loc3='Areatrigger ID %u nicht gefunden!' WHERE entry=262;
UPDATE trinity_string SET content_loc3='Target map oder Koordinaten sind ungültig (X: %f Y: %f MapId: %u)' WHERE entry=263;
UPDATE trinity_string SET content_loc3='Zone Koordinaten sind ungültig (X: %f Y: %f AreaId: %u)' WHERE entry=264;
UPDATE trinity_string SET content_loc3='Zone %u (%s) ist ein Teil der Instanzkarte %u (%s)' WHERE entry=265;
UPDATE trinity_string SET content_loc3='Nichts gefunden!' WHERE entry=266;
UPDATE trinity_string SET content_loc3='Objekt nicht gefunden!' WHERE entry=267;
UPDATE trinity_string SET content_loc3='Kreatur nicht gefunden!' WHERE entry=268;
UPDATE trinity_string SET content_loc3='Warnung: Kreatur mehr als einmal gefunden - Ihr werdet zur ersten teleportiert, die in der Datenbank gefunden wurde.' WHERE entry=269;
UPDATE trinity_string SET content_loc3='Kreatur entfernt.' WHERE entry=270;
UPDATE trinity_string SET content_loc3='Kreatur verschoben.' WHERE entry=271;
UPDATE trinity_string SET content_loc3='Kreatur (GUID:%u) muss auf derselben Karte sein wie der Spieler!' WHERE entry=272;
UPDATE trinity_string SET content_loc3='Gameobjekt (GUID: %u) nicht gefunden' WHERE entry=273;
UPDATE trinity_string SET content_loc3='Gameobjekt (GUID: %u) ist abhängig von der nicht gefundenen Kreatur %u GO list, kann nicht gelöscht werden.' WHERE entry=274;
UPDATE trinity_string SET content_loc3='Gameobjekt (GUID: %u) entfernt' WHERE entry=275;
UPDATE trinity_string SET content_loc3='Gameobjekt |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) gedreht' WHERE entry=276;
UPDATE trinity_string SET content_loc3='Gameobjekt |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) verschoben' WHERE entry=277;
UPDATE trinity_string SET content_loc3='Ihr müsst einen Verkäufer anwählen' WHERE entry=278;
UPDATE trinity_string SET content_loc3='Ihr müsst die ID für das Item angeben' WHERE entry=279;
UPDATE trinity_string SET content_loc3='Verkäufer hat zu viele Items (maximal 128)' WHERE entry=280;
UPDATE trinity_string SET content_loc3='Ihr könnt Euch nicht selbst kicken, loggt Euch stattdessen aus' WHERE entry=281;
UPDATE trinity_string SET content_loc3='Spieler %s wurde gekickt.' WHERE entry=282;
UPDATE trinity_string SET content_loc3='Ihr habt dem Spieler %s das chatten für %u Minuten gesperrt, beginnend mit dem nächsten Login des Spielers. Grund: %s.' WHERE entry=283;
UPDATE trinity_string SET content_loc3='Flüstern erlauben: %s' WHERE entry=284;
UPDATE trinity_string SET content_loc3='Flüstern erlauben: AN (ON)' WHERE entry=285;
UPDATE trinity_string SET content_loc3='Flüstern erlauben: AUS (OFF)' WHERE entry=286;
UPDATE trinity_string SET content_loc3='Kreatur (GUID: %u) nicht gefunden' WHERE entry=287;
UPDATE trinity_string SET content_loc3='Anzahl der Tickets: %i zeige neue Tickets: %s' WHERE entry=288;
UPDATE trinity_string SET content_loc3='Neues Ticket von %s' WHERE entry=289;
UPDATE trinity_string SET content_loc3='Ticket von %s (Letzte aktuallisierung: %s):\n%s' WHERE entry=290;
UPDATE trinity_string SET content_loc3='Neue Tickets zeigen: AN' WHERE entry=291;
UPDATE trinity_string SET content_loc3='Neue Tickets zeigen: AUS' WHERE entry=292;
UPDATE trinity_string SET content_loc3='Ticket %i existiert nicht' WHERE entry=293;
UPDATE trinity_string SET content_loc3='Alle Tickets wurden gelöscht.' WHERE entry=294;
UPDATE trinity_string SET content_loc3='Das Ticket von %s wurde gelöscht.' WHERE entry=295;
UPDATE trinity_string SET content_loc3='Ticket gelöscht.' WHERE entry=296;
UPDATE trinity_string SET content_loc3='Spawndistanz wurde auf %f abgeändert' WHERE entry=297;
UPDATE trinity_string SET content_loc3='Spawnzeit wurde auf: %i abgeändert' WHERE entry=298;
UPDATE trinity_string SET content_loc3='Die Ehre von %s wurde auf %u gesetzt!' WHERE entry=299;
UPDATE trinity_string SET content_loc3='Euer Chat wurde für %u Minuten abgeschaltet. Grund: %s' WHERE entry=300;
UPDATE trinity_string SET content_loc3='Ihr hab den Chat von %s für %u Minuten abgeschaltet. Grund: %s' WHERE entry=301;
UPDATE trinity_string SET content_loc3='Der Chat des Spielers ist bereits eingeschaltet.' WHERE entry=302;
UPDATE trinity_string SET content_loc3='Euer Chat wurde eingeschaltet.' WHERE entry=303;
UPDATE trinity_string SET content_loc3='Ihr habt den Chat von %s eingeschaltet.' WHERE entry=304;
UPDATE trinity_string SET content_loc3='Fraktion %s (%u) Ruf von %s wurde auf %5d gesetzt!' WHERE entry=305;
UPDATE trinity_string SET content_loc3='Die Arenapunkte von %s wurden auf %u gesetzt!' WHERE entry=306;
UPDATE trinity_string SET content_loc3='Keine Fraktion gefunden!' WHERE entry=307;
UPDATE trinity_string SET content_loc3='Fraktion %i unbekannt!' WHERE entry=308;
UPDATE trinity_string SET content_loc3='Ungültiger Parameter %s' WHERE entry=309;
UPDATE trinity_string SET content_loc3='delta muss sich zwischen 0 und %d (inklusive) befinden' WHERE entry=310;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE entry=311;
UPDATE trinity_string SET content_loc3=' [sichtbar]' WHERE entry=312;
UPDATE trinity_string SET content_loc3=' [im Krieg]' WHERE entry=313;
UPDATE trinity_string SET content_loc3=' [friedlich]' WHERE entry=314;
UPDATE trinity_string SET content_loc3=' [versteckt]' WHERE entry=315;
UPDATE trinity_string SET content_loc3=' [unsichtbar]' WHERE entry=316;
UPDATE trinity_string SET content_loc3=' [inaktiv]' WHERE entry=317;
UPDATE trinity_string SET content_loc3='haßerfüllt' WHERE entry=318;
UPDATE trinity_string SET content_loc3='feindselig' WHERE entry=319;
UPDATE trinity_string SET content_loc3='unfreundlich' WHERE entry=320;
UPDATE trinity_string SET content_loc3='neutral' WHERE entry=321;
UPDATE trinity_string SET content_loc3='freundlich' WHERE entry=322;
UPDATE trinity_string SET content_loc3='wohlwollend' WHERE entry=323;
UPDATE trinity_string SET content_loc3='respektvoll' WHERE entry=324;
UPDATE trinity_string SET content_loc3='ehrfürchtig' WHERE entry=325;
UPDATE trinity_string SET content_loc3='Fraktion %s (%u) kann keinen Ruf haben.' WHERE entry=326;
UPDATE trinity_string SET content_loc3=' [kein Ruf]' WHERE entry=327;
UPDATE trinity_string SET content_loc3='Charaktere auf Account %s (Id: %u)' WHERE entry=328;
UPDATE trinity_string SET content_loc3='  %s (GUID %u)' WHERE entry=329;
UPDATE trinity_string SET content_loc3='Keine Spieler gefunden!' WHERE entry=330;
UPDATE trinity_string SET content_loc3='Erweiterte Itemkosten %u existieren nicht' WHERE entry=331;
UPDATE trinity_string SET content_loc3='GM-Modus ist AN' WHERE entry=332;
UPDATE trinity_string SET content_loc3='GM-Modus ist AUS' WHERE entry=333;
UPDATE trinity_string SET content_loc3='GM Anzeige im Chat ist AN' WHERE entry=334;
UPDATE trinity_string SET content_loc3='GM Anzeige im Chat ist AUS' WHERE entry=335;
UPDATE trinity_string SET content_loc3='Ihr repariert alle Gegenstände von %s.' WHERE entry=336;
UPDATE trinity_string SET content_loc3='Alle eure Gegenstände wurden von %s repariert.' WHERE entry=337;
UPDATE trinity_string SET content_loc3='Ihr habt den Wasserlaufen-Modus %s für %s gesetzt.' WHERE entry=338;
UPDATE trinity_string SET content_loc3='Euer Wasserlaufen-Modus %s von %s.' WHERE entry=339;
UPDATE trinity_string SET content_loc3='%s folgt Euch jetzt.' WHERE entry=340;
UPDATE trinity_string SET content_loc3='%s folgt Euch nicht.' WHERE entry=341;
UPDATE trinity_string SET content_loc3='%s folgt Euch jetzt nicht.' WHERE entry=342;
UPDATE trinity_string SET content_loc3='Kreatur (Entry: %u) kann nicht gezähmt werden.' WHERE entry=343;
UPDATE trinity_string SET content_loc3='Ihr habt bereits einen Begleiter.' WHERE entry=344;
UPDATE trinity_string SET content_loc3='Der Spieler %s muss beim nächsten Login umgestaltet werden.' WHERE entry=345;
UPDATE trinity_string SET content_loc3='Der Spieler %s (GUID #%u) muss beim nächsten Login umgestaltet werden.' WHERE entry=346;
UPDATE trinity_string SET content_loc3='Flugpunkt/Anlegestelle ID %u nicht gefunden.' WHERE entry=347;
UPDATE trinity_string SET content_loc3='Gameobjekt (Entry: %u) hat ungültige Daten und kann nicht  gespawned werden.' WHERE entry=348;
UPDATE trinity_string SET content_loc3='%d (idx:%d) - |cffffffff|Htitle:%d|h[%s %s]|h|r %s %s ' WHERE entry=349;
UPDATE trinity_string SET content_loc3='%d (idx:%d) - [%s %s] %s %s ' WHERE entry=350;
UPDATE trinity_string SET content_loc3='Keine Titel gefunden!' WHERE entry=351;
UPDATE trinity_string SET content_loc3='Ungültige Titel-Id: %u' WHERE entry=352;
UPDATE trinity_string SET content_loc3='Der Titel %u (%s) wurde dem Spieler %s zu seiner Titelliste hinzugefügt.' WHERE entry=353;
UPDATE trinity_string SET content_loc3='Der Titel %u (%s) wurde dem Spieler %s aus seiner Titelliste entfernt.' WHERE entry=354;
UPDATE trinity_string SET content_loc3='Der Titel %u (%s) ist jetzt der aktive Titel von Spieler %s.' WHERE entry=355;
UPDATE trinity_string SET content_loc3='Der aktive Titel von Spieler %s wurde zurückgesetzt.' WHERE entry=356;
UPDATE trinity_string SET content_loc3='|cffff0000[System-Nachricht]:|rScripts neu geladen' WHERE entry=400;
UPDATE trinity_string SET content_loc3='Ihr ändert die Berechtigungsstufe von %s auf %i.' WHERE entry=401;
UPDATE trinity_string SET content_loc3='%s hat Eure Berechtigungsstufe auf %i geändert.' WHERE entry=402;
UPDATE trinity_string SET content_loc3='Ihr habt dafür eine zu niedrige Berechtigungsstufe.' WHERE entry=403;
UPDATE trinity_string SET content_loc3='Kreaturenbewegung abgeschaltet.' WHERE entry=404;
UPDATE trinity_string SET content_loc3='Kreaturenbewegung angeschaltet.' WHERE entry=405;
UPDATE trinity_string SET content_loc3='Wetter kann für diese Zone nicht geändert werden.' WHERE entry=406;
UPDATE trinity_string SET content_loc3='Wettersystem ist auf dem Server abgeschaltet.' WHERE entry=407;
UPDATE trinity_string SET content_loc3='%s ist gebannt für %s. Grund: %s.' WHERE entry=408;
UPDATE trinity_string SET content_loc3='%s ist für immer gebannt für %s.' WHERE entry=409;
UPDATE trinity_string SET content_loc3='%s %s nicht gefunden' WHERE entry=410;
UPDATE trinity_string SET content_loc3='%s Bann wurde aufgehoben.' WHERE entry=411;
UPDATE trinity_string SET content_loc3='Ein Fehler ist beim Entfernen des Banns von %s aufgetreten.' WHERE entry=412;
UPDATE trinity_string SET content_loc3='Es gibt keinen solchen Account: %s' WHERE entry=413;
UPDATE trinity_string SET content_loc3='Es gibt keinen solchen Charakter.' WHERE entry=414;
UPDATE trinity_string SET content_loc3='Es gibt keine solche IP in der Bannliste.' WHERE entry=415;
UPDATE trinity_string SET content_loc3='Account %s wurde niemals gebannt' WHERE entry=416;
UPDATE trinity_string SET content_loc3='Bannhistory für den Account %s:' WHERE entry=417;
UPDATE trinity_string SET content_loc3='Banndatum: %s Bannzeit: %s Noch aktiv: %s  Grund: %s Von: %s' WHERE entry=418;
UPDATE trinity_string SET content_loc3='Inf.' WHERE entry=419;
UPDATE trinity_string SET content_loc3='Niemals' WHERE entry=420;
UPDATE trinity_string SET content_loc3='Ja' WHERE entry=421;
UPDATE trinity_string SET content_loc3='Nein' WHERE entry=422;
UPDATE trinity_string SET content_loc3='IP: %s\nBanndatum: %s\nEntbanndatum: %s\nVerbleibend: %s\nGrund: %s\nVon: %s' WHERE entry=423;
UPDATE trinity_string SET content_loc3='Es gibt keinen passenden IP-Bann.' WHERE entry=424;
UPDATE trinity_string SET content_loc3='Es gibt keinen passenden Account.' WHERE entry=425;
UPDATE trinity_string SET content_loc3='Es gibt keinen gebannten Account dem ein Charakter gehört, der mit diesem Suchmuster übereinstimmt.' WHERE entry=426;
UPDATE trinity_string SET content_loc3='Die folgenden IPs entsprechende Eurem Muster:' WHERE entry=427;
UPDATE trinity_string SET content_loc3='Die folgenden Accounts stimmen mit ihrer Abfrage überein:' WHERE entry=428;
UPDATE trinity_string SET content_loc3='Ihr habt viele Zauber/Fertigkeiten gelernt.' WHERE entry=429;
UPDATE trinity_string SET content_loc3='Ihr habt alle Zauber für Eure Klasse gelernt.' WHERE entry=430;
UPDATE trinity_string SET content_loc3='Ihr habt alle Talente für Eure Klasse gelernt.' WHERE entry=431;
UPDATE trinity_string SET content_loc3='Ihr habt alle Sprachen gelernt.' WHERE entry=432;
UPDATE trinity_string SET content_loc3='Ihr habt alle Berufsfertigkeiten und Rezepte gelernt.' WHERE entry=433;
UPDATE trinity_string SET content_loc3='Konnte \'%s\' nicht finden' WHERE entry=434;
UPDATE trinity_string SET content_loc3='Ungültige Item-ID: %u' WHERE entry=435;
UPDATE trinity_string SET content_loc3='Keine Items gefunden!' WHERE entry=436;
UPDATE trinity_string SET content_loc3='Ungültige Gameobject-Id: %u' WHERE entry=437;
UPDATE trinity_string SET content_loc3='Gefundene Items %u: %u ( Inventar %u Mail %u Auktion %u Gilde %u)' WHERE entry=438;
UPDATE trinity_string SET content_loc3='Gefundene Gameobjects %u: %u ' WHERE entry=439;
UPDATE trinity_string SET content_loc3='Ungültige Kreatur-ID: %u' WHERE entry=440;
UPDATE trinity_string SET content_loc3='Gefundene Kreaturen %u: %u ' WHERE entry=441;
UPDATE trinity_string SET content_loc3='Kein Gebiet gefunden!' WHERE entry=442;
UPDATE trinity_string SET content_loc3='Keine Itemsets gefunden!' WHERE entry=443;
UPDATE trinity_string SET content_loc3='Keine Fertigkeiten gefunden!' WHERE entry=444;
UPDATE trinity_string SET content_loc3='Keine Zauber gefunden!' WHERE entry=445;
UPDATE trinity_string SET content_loc3='Keine Quests gefunden!' WHERE entry=446;
UPDATE trinity_string SET content_loc3='Keine Kreaturen gefunden!' WHERE entry=447;
UPDATE trinity_string SET content_loc3='Keine Gameobjects gefunden!' WHERE entry=448;
UPDATE trinity_string SET content_loc3='Friedhof #%u existiert nicht.' WHERE entry=449;
UPDATE trinity_string SET content_loc3='Friedhof #%u ist bereits mit der Zone #%u (aktuell) verlinkt.' WHERE entry=450;
UPDATE trinity_string SET content_loc3='Friedhof #%u mit der Zone #%u (aktuell) verlinkt.' WHERE entry=451;
UPDATE trinity_string SET content_loc3='Friedhof #%u kann nicht mit der Unterzone oder mit einer nicht existierenden Zone #%u verlinkt werden (Interner Fehler).' WHERE entry=452;
UPDATE trinity_string SET content_loc3='Verbleibende Ban Zeit: %s, Gebannt von: %s, Grund: %s' WHERE entry=453;
UPDATE trinity_string SET content_loc3='Keine Fraktion im Friedhof mit id= #%u , repariert Eure Datenbank' WHERE entry=454;
UPDATE trinity_string SET content_loc3='Ungültiges Team, bitte repariert Eure Datenbank' WHERE entry=455;
UPDATE trinity_string SET content_loc3='beliebig' WHERE entry=456;
UPDATE trinity_string SET content_loc3='Allianz' WHERE entry=457;
UPDATE trinity_string SET content_loc3='Horde' WHERE entry=458;
UPDATE trinity_string SET content_loc3='Friedhof #%u (faction: %s) ist der nächste der zur Zone #%u gehört.' WHERE entry=459;
UPDATE trinity_string SET content_loc3='Zone #%u hat keinen verlinkten Friedhof.' WHERE entry=460;
UPDATE trinity_string SET content_loc3='Zone #%u hat keinen verlinkten Friedhof für die Fraktion: %s.' WHERE entry=461;
UPDATE trinity_string SET content_loc3='Teleportierort existiert bereits!' WHERE entry=462;
UPDATE trinity_string SET content_loc3='Teleportierort hinzugefügt.' WHERE entry=463;
UPDATE trinity_string SET content_loc3='Teleportierort NICHT hinzugefügt: Datenbankfehler.' WHERE entry=464;
UPDATE trinity_string SET content_loc3='Teleportierort entfernt.' WHERE entry=465;
UPDATE trinity_string SET content_loc3='Keine Flugpunkte gefunden.' WHERE entry=466;
UPDATE trinity_string SET content_loc3='Angewählte Einheit hat %d Auren:' WHERE entry=467;
UPDATE trinity_string SET content_loc3='id: %d %s effmask: %d charges: %d stack: %d slot %d duration: %d maxduration: %d %s %s caster: %s guid: %d' WHERE entry=468;
UPDATE trinity_string SET content_loc3='Angewählte Einheit hat %d Auren des Typs %d:' WHERE entry=469;
UPDATE trinity_string SET content_loc3='id: %d eff: %d amount: %d' WHERE entry=470;
UPDATE trinity_string SET content_loc3='Quest %u nicht gefunden.' WHERE entry=471;
UPDATE trinity_string SET content_loc3='Quest %u wird von einem Item gestartet. Damit dieser korrekt funktioniert, startet ihn bitte, indem Ihr das Item zu Eurem Inventar hinzufügt und den Quest auf dem normalen Weg startet: .additem %u' WHERE entry=472;
UPDATE trinity_string SET content_loc3='Quest entfernt.' WHERE entry=473;
UPDATE trinity_string SET content_loc3=' [belohnt]' WHERE entry=474;
UPDATE trinity_string SET content_loc3=' [fertig]' WHERE entry=475;
UPDATE trinity_string SET content_loc3=' [aktiv]' WHERE entry=476;
UPDATE trinity_string SET content_loc3='%s\'s Flugmodus %s' WHERE entry=477;
UPDATE trinity_string SET content_loc3='Opcode %u gesendet an %s' WHERE entry=478;
UPDATE trinity_string SET content_loc3='Charakter erfolgreich geladen!' WHERE entry=479;
UPDATE trinity_string SET content_loc3='Laden des Charakters gescheitert!' WHERE entry=480;
UPDATE trinity_string SET content_loc3='Charakter erfolgreich exportiert!' WHERE entry=481;
UPDATE trinity_string SET content_loc3='Exportieren des Charakters gescheitert!' WHERE entry=482;
UPDATE trinity_string SET content_loc3='Zauber %u ist defekt  und es ist nicht erlaubt ihn zu verwenden oder zu lernen!' WHERE entry=483;
UPDATE trinity_string SET content_loc3='Fertigkeit %u (%s) für den Spieler %s auf %u gesetzt und derzeitiges Maximum auf %u gesetzt (ohne dauerhafte (Talent-) Boni).' WHERE entry=484;
UPDATE trinity_string SET content_loc3='Spieler %s muss die Fertigkeit %u (%s) haben, bevor er diesen Befehl verwenden kann.' WHERE entry=485;
UPDATE trinity_string SET content_loc3='Ungültige Fertigkeits-ID (%u)' WHERE entry=486;
UPDATE trinity_string SET content_loc3='Ihr habt alle vorgegebenen GM Zauber/Fertigkeiten gelernt.' WHERE entry=487;
UPDATE trinity_string SET content_loc3='Ihr kennt diesen Zauber bereits.' WHERE entry=488;
UPDATE trinity_string SET content_loc3='Ziel(%s) kennt diesen Zauber bereits.' WHERE entry=489;
UPDATE trinity_string SET content_loc3='%s kennt diesen Zauber nicht.' WHERE entry=490;
UPDATE trinity_string SET content_loc3='Ihr habt diesen Zauber bereits vergessen.' WHERE entry=491;
UPDATE trinity_string SET content_loc3='Alle Zauber-Abklingzeiten wurden für %s entfernt.' WHERE entry=492;
UPDATE trinity_string SET content_loc3='Zauber %u Abklingzeit entfernt für %s.' WHERE entry=493;
UPDATE trinity_string SET content_loc3='Befehl : additem, itemId = %i, amount = %i' WHERE entry=494;
UPDATE trinity_string SET content_loc3='Befehl : additemset, itemsetId = %i' WHERE entry=495;
UPDATE trinity_string SET content_loc3='Entferne itemID %i, Anzahl %i von %s' WHERE entry=496;
UPDATE trinity_string SET content_loc3='Kann Item \'%i\' (Anzahl: %i) nicht herstellen' WHERE entry=497;
UPDATE trinity_string SET content_loc3='Ihr müsst einen Gildennamen bestimmen!' WHERE entry=498;
UPDATE trinity_string SET content_loc3='Spieler nicht gefunden!' WHERE entry=499;
UPDATE trinity_string SET content_loc3='Spieler hat bereits eine Gilde!' WHERE entry=500;
UPDATE trinity_string SET content_loc3='Gilde wurde nicht erstellt! (Vielleicht existiert bereits eine Gilde mit diesem Namen?)' WHERE entry=501;
UPDATE trinity_string SET content_loc3='Kein Item vom Itemset \'%u\' gefunden.' WHERE entry=502;
UPDATE trinity_string SET content_loc3='Die Entfernung ist: (3D) %f (2D) %f (Exact 3D) %f (Exact 2D) %f yards.' WHERE entry=503;
UPDATE trinity_string SET content_loc3='Item \'%i\' \'%s\' Item Slot %i' WHERE entry=504;
UPDATE trinity_string SET content_loc3='Item \'%i\' existiert nicht.' WHERE entry=505;
UPDATE trinity_string SET content_loc3='Item \'%i\' \'%s\' zum Slot %i hinzugefügt' WHERE entry=506;
UPDATE trinity_string SET content_loc3='Sicherung des Items fehlgeschlagen!' WHERE entry=507;
UPDATE trinity_string SET content_loc3='%d - Besitzer: %s (Guid: %u Account: %u ) %s' WHERE entry=508;
UPDATE trinity_string SET content_loc3='%d - Absender: %s (Guid: %u Account: %u ) Empfänger: %s (Guid: %u Account: %u ) %s' WHERE entry=509;
UPDATE trinity_string SET content_loc3='%d - Besitzer: %s (Guid: %u Account: %u ) %s' WHERE entry=510;
UPDATE trinity_string SET content_loc3='Falscher Linktyp!' WHERE entry=511;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r ' WHERE entry=512;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE entry=513;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' WHERE entry=514;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=515;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' WHERE entry=516;
UPDATE trinity_string SET content_loc3='%d (Eintrag: %d) - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE `entry` = 517;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' WHERE entry=518;
UPDATE trinity_string SET content_loc3='|cffffffff|Htele:%s|h[%s]|h|r ' WHERE entry=519;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hspell:%d|h[%s]|h|r ' WHERE entry=520;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE entry=521;
UPDATE trinity_string SET content_loc3='Gameobjekt (Entry: %u) nicht gefunden' WHERE entry=522;
UPDATE trinity_string SET content_loc3='>> Gameobjekt %s (GUID: %u) bei %f %f %f. Orientierung %f.' WHERE entry=523;
UPDATE trinity_string SET content_loc3='Ausgewähltes Objekt:\n|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u\nX: %f Y: %f Z: %f MapId: %u\nOrientierung: %f\nPhasemask %u' WHERE entry=524;
UPDATE trinity_string SET content_loc3='>> Füge Game Object \'%i\' (%s) (GUID: %i) hinzu zu. Position: \'%f %f %f\'.' WHERE entry=525;
UPDATE trinity_string SET content_loc3='%s (lowguid: %u) Bewegungsgeneratoren:' WHERE entry=526;
UPDATE trinity_string SET content_loc3='   leer' WHERE entry=527;
UPDATE trinity_string SET content_loc3='   zufällig' WHERE entry=528;
UPDATE trinity_string SET content_loc3='   Wegepunkt' WHERE entry=529;
UPDATE trinity_string SET content_loc3='   zufälliges Tier' WHERE entry=530;
UPDATE trinity_string SET content_loc3='   Verwirrt' WHERE entry=531;
UPDATE trinity_string SET content_loc3='   Gezielt auf den Spieler %s (lowguid %u)' WHERE entry=532;
UPDATE trinity_string SET content_loc3='   Gezielt auf die Kreatur %s (lowguid %u)' WHERE entry=533;
UPDATE trinity_string SET content_loc3='   Gezielt auf <NULL>' WHERE entry=534;
UPDATE trinity_string SET content_loc3='   Bewegung zum Startpunkt (X:%f Y:%f Z:%f)' WHERE entry=535;
UPDATE trinity_string SET content_loc3='   Bewegung zum Startpunkt für Spieler?!?' WHERE entry=536;
UPDATE trinity_string SET content_loc3='   Flugroute' WHERE entry=537;
UPDATE trinity_string SET content_loc3='   Unbekannter Bewegungsgenerator (%u)' WHERE entry=538;
UPDATE trinity_string SET content_loc3='Spieler hat folgenden NPC angewählt\nDB GUID: %u, aktuelle GUID: %u.\nFaction: %u.\nnpcFlags: %u.\nEntry: %u.\nDisplayID: %u (Native: %u).' WHERE entry=539;
UPDATE trinity_string SET content_loc3='Level: %u.' WHERE entry=540;
UPDATE trinity_string SET content_loc3='Leben (Basis): %u. (max): %u. (aktuell): %u.' WHERE entry=541;
UPDATE trinity_string SET content_loc3='Field Flags: %u.\nDynamic Flags: %u.\nFaction Template: %u.' WHERE entry=542;
UPDATE trinity_string SET content_loc3='Loot: %u Taschendiebstahl: %u Kürschnerei: %u' WHERE entry=543;
UPDATE trinity_string SET content_loc3='Position: %f %f %f.' WHERE entry=544;
UPDATE trinity_string SET content_loc3='*** Ist ein Verkäufer!' WHERE entry=545;
UPDATE trinity_string SET content_loc3='*** Ist ein Trainer!' WHERE entry=546;
UPDATE trinity_string SET content_loc3='InstanceID: %u' WHERE entry=547;
UPDATE trinity_string SET content_loc3='Spieler%s %s (guid: %u) Account: %s (id: %u) Email: %s GMLevel: %u Letzte IP: %s Letzter Login: %s Latenz: %ums' WHERE entry=548;
UPDATE trinity_string SET content_loc3='Rasse: %s Klasse: %s Gespielte Zeit: %s Level: %u Geld: %ug%us%uc' WHERE entry=549;
UPDATE trinity_string SET content_loc3='Restliche Mute (Chatverbot) Zeit: %s.' WHERE entry=550;
UPDATE trinity_string SET content_loc3='%s hat nun alle Zonen aufgedeckt.' WHERE entry=551;
UPDATE trinity_string SET content_loc3='%s hat nun nicht mehr alle Zonen aufgedeckt.' WHERE entry=552;
UPDATE trinity_string SET content_loc3='%s hat alle Zonen für Euch aufgedeckt.' WHERE entry=553;
UPDATE trinity_string SET content_loc3='%s hat alle Zonen vor Euch verborgen.' WHERE entry=554;

UPDATE trinity_string SET content_loc3='%s hat euren Level auf (%i) erhöht' WHERE entry=557;
UPDATE trinity_string SET content_loc3='%s hat euren Level auf (%i) verringert' WHERE entry=558;
UPDATE trinity_string SET content_loc3='%s hat euren Levelfortschritt zurückgesetzt.' WHERE entry=559;
UPDATE trinity_string SET content_loc3='Das Gebiet wurde als entdeckt gesetzt.' WHERE entry=560;
UPDATE trinity_string SET content_loc3='Das Gebiet wurde als nicht entdeckt gesetzt.' WHERE entry=561;
UPDATE trinity_string SET content_loc3='GUID=%i \'s updateIndex: %i, Wert:  %i.' WHERE entry=562;
UPDATE trinity_string SET content_loc3='Ihr ändert GUID=%i \'s UpdateIndex: %i Wert auf %i.' WHERE entry=563;
UPDATE trinity_string SET content_loc3='Der Wert des Index %u ist zu groß %u(Anzahl: %u).' WHERE entry=564;
UPDATE trinity_string SET content_loc3='Setze %u uint32 Wert:[OPCODE]:%u [VALUE]:%u' WHERE entry=565;
UPDATE trinity_string SET content_loc3='Ihr setzt %u Field:%u auf uint32 Wert: %u' WHERE entry=566;
UPDATE trinity_string SET content_loc3='Setze %u float Wert:[OPCODE]:%u [VALUE]:%f' WHERE entry=567;
UPDATE trinity_string SET content_loc3='Ihr setzt %u Field:%i auf float Wert: %f' WHERE entry=568;
UPDATE trinity_string SET content_loc3='Zeige %u uint32 Wert:[OPCODE]:%u [VALUE]:%u' WHERE entry=569;
UPDATE trinity_string SET content_loc3='Der uint32 Wert von %u in %u ist: %u' WHERE entry=570;
UPDATE trinity_string SET content_loc3='Zeige %u float Wert:[OPCODE]:%u [VALUE]:%f' WHERE entry=571;
UPDATE trinity_string SET content_loc3='Der float von %u Wert in %u ist: %f' WHERE entry=572;
UPDATE trinity_string SET content_loc3='.Set32Bit:[OPCODE]:%u [VALUE]:%u' WHERE entry=573;
UPDATE trinity_string SET content_loc3='Ihr setzt Bit von Field:%u auf Wert: %u' WHERE entry=574;
UPDATE trinity_string SET content_loc3='.Mod32Value:[OPCODE]:%u [VALUE]:%i' WHERE entry=575;
UPDATE trinity_string SET content_loc3='Ihr habt den Wert des Feldes:%u auf den Wert: %u geändert' WHERE entry=576;
UPDATE trinity_string SET content_loc3='Ihr seid jetzt unsichtbar.' WHERE entry=577;
UPDATE trinity_string SET content_loc3='Ihr seid jetzt sichtbar.' WHERE entry=578;
UPDATE trinity_string SET content_loc3='Angewählter Spieler oder Kreatur haben kein Opfer.' WHERE entry=579;
UPDATE trinity_string SET content_loc3='Spieler %s hat alle Standardzauber seiner Rasse/Klasse und Zauber, die er durch abgeschlossenen Quests bekam, erlernt.' WHERE entry=580;
UPDATE trinity_string SET content_loc3='Gefundene Gameobjecte in der Nähe (Distanz %f): %u ' WHERE entry=581;
UPDATE trinity_string SET content_loc3='SpawnTime: Gesamt:%s Verbleibend:%s' WHERE entry=582;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s' WHERE entry=583;
UPDATE trinity_string SET content_loc3='Kein Event gefunden!' WHERE entry=584;
UPDATE trinity_string SET content_loc3='Das Event existiert nicht!' WHERE entry=585;
UPDATE trinity_string SET content_loc3='Event %u: %s%s\nStart: %s Ende: %s Häufigkeit: %s Länge: %s\nNächster Statuswechsel: %s' WHERE entry=586;
UPDATE trinity_string SET content_loc3='Event %u bereits aktiv!' WHERE entry=587;
UPDATE trinity_string SET content_loc3='Event %u nicht aktiv!' WHERE entry=588;
UPDATE trinity_string SET content_loc3='   Punktbewegung nach (X:%f Y:%f Z:%f)' WHERE entry=589;
UPDATE trinity_string SET content_loc3='   Furchtbewegung' WHERE entry=590;
UPDATE trinity_string SET content_loc3='   Ablenkungsbewegung' WHERE entry=591;
UPDATE trinity_string SET content_loc3='Ihr habt alle Zauber in folgendem Handwerk erlernt: %s' WHERE entry=592;
UPDATE trinity_string SET content_loc3='Zurzeit gebannte Benutzerkonten:' WHERE entry=593;
UPDATE trinity_string SET content_loc3='|    Account    |  BanDatum    |  UnbanDatum  | Gebannt von   |     Grund     |' WHERE entry=594;
UPDATE trinity_string SET content_loc3='Zurzeit gebannte IPs:' WHERE entry=595;
UPDATE trinity_string SET content_loc3='|      IP       |  BanDatum    |  UnbanDatum  | Gebannt von   |     Grund     |' WHERE entry=596;
UPDATE trinity_string SET content_loc3='Aktuelle Gamemaster:' WHERE entry=597;
UPDATE trinity_string SET content_loc3='|    Account    |  GM  |' WHERE entry=598;
UPDATE trinity_string SET content_loc3='Keine Gamemaster vorhanden.' WHERE entry=599;
UPDATE trinity_string SET content_loc3='Die Allianz gewinnt!' WHERE entry=600;
UPDATE trinity_string SET content_loc3='Die Horde gewinnt!' WHERE entry=601;
UPDATE trinity_string SET content_loc3='Die Schlacht der Kriegshymnenschlucht beginnt in 1 Minute.' WHERE entry=602;
UPDATE trinity_string SET content_loc3='Die Schlacht der Kriegshymnenschlucht beginnt in 30 Sekunden. Bereitet Euch vor!' WHERE entry=603;
UPDATE trinity_string SET content_loc3='Lasst die Schlacht der Kriegshymnenschlucht beginnen!' WHERE entry=604;
UPDATE trinity_string SET content_loc3='$n erobert die Flagge der Horde!' WHERE entry=605;
UPDATE trinity_string SET content_loc3='$n erobert die Flagge der Allianz!' WHERE entry=606;
UPDATE trinity_string SET content_loc3='Die Flagge der Horde wurde von $n fallen gelassen!' WHERE entry=607;
UPDATE trinity_string SET content_loc3='Die Flagge der Allianz wurde von $n fallen gelassen!' WHERE entry=608;
UPDATE trinity_string SET content_loc3='Die Flagge der Allianz wurde zurück zur Basis gebracht von $n!' WHERE entry=609;
UPDATE trinity_string SET content_loc3='Die Flagge der Horde wurde zurück zur Basis gebracht von $n!' WHERE entry=610;
UPDATE trinity_string SET content_loc3='Die Flagge der Horde wurde von $n aufgenommen!' WHERE entry=611;
UPDATE trinity_string SET content_loc3='Die Flagge der Allianz wurde von $n aufgenommen!' WHERE entry=612;
UPDATE trinity_string SET content_loc3='Die Flaggen sind jetzt an ihren Basen.' WHERE entry=613;
UPDATE trinity_string SET content_loc3='Die Flagge der Allianz ist an ihrer Basis!' WHERE entry=614;
UPDATE trinity_string SET content_loc3='Die Flagge der Horde ist an ihrer Basis!' WHERE entry=615;
UPDATE trinity_string SET content_loc3='Der Kampf im Auge des Sturms beginnt in 1 Minute.' WHERE entry=636;
UPDATE trinity_string SET content_loc3='Der Kampf im Auge des Sturms beginnt in 30 Sekunden.' WHERE entry=637;
UPDATE trinity_string SET content_loc3='Der Kampf im Auge des Sturms hat begonnen!' WHERE entry=638;
UPDATE trinity_string SET content_loc3='Allianz' WHERE entry=650;
UPDATE trinity_string SET content_loc3='Horde' WHERE entry=651;
UPDATE trinity_string SET content_loc3='Stallungen' WHERE entry=652;
UPDATE trinity_string SET content_loc3='Schmied' WHERE entry=653;
UPDATE trinity_string SET content_loc3='Farm' WHERE entry=654;
UPDATE trinity_string SET content_loc3='Sägewerk' WHERE entry=655;
UPDATE trinity_string SET content_loc3='Mine' WHERE entry=656;
UPDATE trinity_string SET content_loc3='Die %s hat %s eingenommen' WHERE entry=657;
UPDATE trinity_string SET content_loc3='$n hat %s verteidigt' WHERE entry=658;
UPDATE trinity_string SET content_loc3='$n hat %s angegriffen' WHERE entry=659;
UPDATE trinity_string SET content_loc3='$n nimmt %s ein! Falls es nicht verteidigt wird, wird die %s es in 1 Minute kontrollieren!' WHERE entry=660;
UPDATE trinity_string SET content_loc3='Die Schlacht des Arathibecken beginnt in 1 Minute.' WHERE entry=661;
UPDATE trinity_string SET content_loc3='Die Schlacht des Arathibecken beginnt in 30 Sekunden. Bereitet Euch vor!' WHERE entry=662;
UPDATE trinity_string SET content_loc3='Die Schlacht des Arathibecken hat begonnen' WHERE entry=663;
UPDATE trinity_string SET content_loc3='Die Allianz hat $1776W an Ressourcen gesammelt und steht kurz vor dem Sieg!' WHERE entry=664;
UPDATE trinity_string SET content_loc3='Die Horde hat $1777W an Ressourcen gesammelt und steht kurz vor dem Sieg!' WHERE entry=665;
UPDATE trinity_string SET content_loc3='Nach deiner letzten Schlacht in %s schlug der Versuch Euch ein Ehrenabzeichen als Belohnung auszuhändigen fehl. Beiliegend findet Ihr das Ehrenabzeichen, welches wir Euch zu dieser Zeit nicht zukommen lassen konnten. Vielen Dank für den Kampf in %s!' WHERE entry=666;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Magierturm übernommen!' WHERE entry=667;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Magierturm übernommen!' WHERE entry=668;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Draeneiruinen übernommen!' WHERE entry=669;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Draeneiruinen übernommen!' WHERE entry=670;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Blutelfenturm übernommen!' WHERE entry=671;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Blutelfenturm übernommen!' WHERE entry=672;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Teufelshäscherruinen übernommen!' WHERE entry=673;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Teufelshäscherruinen übernommen!' WHERE entry=674;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Magierturm verloren!' WHERE entry=675;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Magierturm verloren!' WHERE entry=676;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Draeneiruinen verloren!' WHERE entry=677;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Draeneiruinen verloren!' WHERE entry=678;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Blutelfenturm verloren!' WHERE entry=679;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Blutelfenturm verloren!' WHERE entry=680;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Teufelshäscherruinen verloren!' WHERE entry=681;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Teufelshäscherruinen verloren!' WHERE entry=682;
UPDATE trinity_string SET content_loc3='%s hat die Flagge aufgenommen!' WHERE entry=683;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Flagge erobert!' WHERE entry=684;
UPDATE trinity_string SET content_loc3='Die Horde hat die Flagge erobert!' WHERE entry=685;
UPDATE trinity_string SET content_loc3='Die Flagge wurde fallengelassen.' WHERE entry=686;
UPDATE trinity_string SET content_loc3='Die Flagge wurde zurückgesetzt.' WHERE entry=687;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %u haben um ein Arenateam zu gründen' WHERE entry=700;
UPDATE trinity_string SET content_loc3='Eine Minute, bis die Arenaschlacht beginnt!' WHERE entry=701;
UPDATE trinity_string SET content_loc3='30 Sekunden, bis die Arenaschlacht beginnt!' WHERE entry=702;
UPDATE trinity_string SET content_loc3='15 Sekunden, bis die Arenaschlacht beginnt!' WHERE entry=703;
UPDATE trinity_string SET content_loc3='Die Arenaschlacht hat begonnen!' WHERE entry=704;
UPDATE trinity_string SET content_loc3='Ihr müsst %s warten bevor Ihr wieder sprechen könnt' WHERE entry=705;
UPDATE trinity_string SET content_loc3='Diese(s) Item(s) hat/haben Probleme mit dem ausrüsten/lagern im Inventar' WHERE entry=706;
UPDATE trinity_string SET content_loc3='%s möchte nicht gestört werden und kann keine Flüsternachrichten erhalten: %s ' WHERE entry=707;
UPDATE trinity_string SET content_loc3='%s ist abwesend von der Tastatur: %s' WHERE entry=708;
UPDATE trinity_string SET content_loc3='Bitte nicht stören.' WHERE entry=709;
UPDATE trinity_string SET content_loc3='Abwesend von der Tastatur' WHERE entry=710;
UPDATE trinity_string SET content_loc3='Warteschlangenstatus für %s (Lvl: %u to %u)\n Warteschlange Allianz: %u (Brauchen noch mindestens %u mehr)\n Warteschlange Horde: %u (Brauchen noch mindestens %u mehr)' WHERE entry=711;
UPDATE trinity_string SET content_loc3='|cffff0000[BG Ansager für Warteschlange]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r' WHERE entry=712;
UPDATE trinity_string SET content_loc3='Ihr müsst Level %u sein, um einem Arenateam beitreten zu können!' WHERE entry=713;
UPDATE trinity_string SET content_loc3='Map: %s, Area: %s, Zone: %s, Phase: %u' WHERE entry=714;
UPDATE trinity_string SET content_loc3='Ihr erfüllt die Vorraussetzungen für das Schlachtfeld nicht' WHERE entry=715;
UPDATE trinity_string SET content_loc3='Map: %s, Area: %s.' WHERE entry=716;
UPDATE trinity_string SET content_loc3='|cffff0000[BG Ansager für Warteschlange]:|r %s -- [%u-%u] beginnt!|r' WHERE entry=717;
UPDATE trinity_string SET content_loc3='|cffff0000[BG Ansager für Warteschlange]:|r %s -- beigetreten : %ux%u : %u|r' WHERE entry=718;
UPDATE trinity_string SET content_loc3='|cffff0000[BG Ansager für Warteschlange]:|r %s -- verlassen : %ux%u : %u|r' WHERE entry=719;
UPDATE trinity_string SET content_loc3='Eure Gruppe ist zu groß für das Schlachtfeld. Bitte macht eine neue Gruppe um beizutreten.' WHERE entry=720;
UPDATE trinity_string SET content_loc3='Eure Gruppe ist zu groß für diese Arena. Bitte macht eine neue Gruppe um beizutreten.' WHERE entry=721;
UPDATE trinity_string SET content_loc3='In eurer Gruppe befinden sich Mitglieder die nicht zu eurem Arena-Team gehören. Bitte macht eine neue Gruppe um beizutreten.' WHERE entry=722;
UPDATE trinity_string SET content_loc3='Eure Gruppe hat nicht genug Spieler um der Schlacht beitreten zu können.' WHERE entry=723;
UPDATE trinity_string SET content_loc3='Das goldene Team gewinnt!' WHERE entry=724;
UPDATE trinity_string SET content_loc3='Das grüne Team gewinnt!' WHERE entry=725;
UPDATE trinity_string SET content_loc3='Es sind nicht genug Spieler auf diesem Schlachtfeld. Daher wird der Kampf bald beendet, es sei denn es treten mehr Spieler dem Kampf bei um das Verhältnis zwischen Allianz und Horde auszugleichen.' WHERE entry=726;
UPDATE trinity_string SET content_loc3='Eure Gruppe hat ein Mitglied das offline ist. Bitte entfernt ihn bevor ihr beitretet.' WHERE entry=727;
UPDATE trinity_string SET content_loc3='Eure Gruppe hat einen Spieler von der andere Fraktion. Ihr könnt nicht als eine Gruppe das Schlachtfeld betreten.' WHERE entry=728;
UPDATE trinity_string SET content_loc3='Eure Gruppe hat einen Spieler der nicht in euere Schlachtfeldlevel passt (1-9,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80).  Ihr könnt nicht als eine Gruppe das Schlachtfeld betreten.' WHERE entry=729;
UPDATE trinity_string SET content_loc3='Irgendjemand in eurer Gruppe ist schon in der Warteschlange für dieses Schlachtfeld. Er/Sie muss diese verlassen um als Gruppe beitreten zu können.' WHERE entry=730;
UPDATE trinity_string SET content_loc3='Irgendjemand in eurer Gruppe ist ein Deserteur. Ihr könnt nicht als Gruppe beitreten.' WHERE entry=731;
UPDATE trinity_string SET content_loc3='Irgendjemand in eurer Gruppe ist schon in 3 Schlachtfeldern angemeldet. Ihr könnt nicht als Gruppe beitreten.' WHERE entry=732;
UPDATE trinity_string SET content_loc3='Ihr könnt euch nicht zu einem Schlachtfeld oder einer Arena-Karte teleportieren.' WHERE entry=733;
UPDATE trinity_string SET content_loc3='Ihr könnt keinen Spieler zu einem Schlachtfeld oder einer Arena-Karte beschwören.' WHERE entry=734;
UPDATE trinity_string SET content_loc3='Ihr müsst im GM-Modus sein um euch zu einem Spieler teleportieren zu können, der sich auf einem Schlachtfeld befindet.' WHERE entry=735;
UPDATE trinity_string SET content_loc3='Ihr könnt euch nicht von einem zum anderen Schlachtfeld teleportieren. Bitte verlasst zuerst das gegenwärtige Schlachtfeld. ' WHERE entry=736;
UPDATE trinity_string SET content_loc3='Zu Testzwecken wurden die Arenaspielerbegrenzung auf 1v1 gesetzt. Nun braucht ihr keine Gruppe mehr.' WHERE entry=737;
UPDATE trinity_string SET content_loc3='Die Arenen wurden auf ihre ursprünglichen Spielerbegrenzungen zurückgesetzt.' WHERE entry=738;
UPDATE trinity_string SET content_loc3='Zu Testzwecken wurden die Schlachtfeldspielerbegrenzung auf 1v0 gesetzt.' WHERE entry=739;
UPDATE trinity_string SET content_loc3='Die Schlachtfelder wurden auf ihre ursprünglichen Spielerbegrenzungen zurückgesetzt.' WHERE entry=740;
UPDATE trinity_string SET content_loc3='Gleiche die Arenapunkte basierend auf den Teamwertungen ab, dies kann einige Minuten dauern. Bitte warten...' WHERE entry=741;
UPDATE trinity_string SET content_loc3='Verteile Arenapunkte auf die Spieler...' WHERE entry=742;
UPDATE trinity_string SET content_loc3='Die Arenapunkte für die Spieler, die online sind, wurden erfolgreich verteilt.' WHERE entry=743;
UPDATE trinity_string SET content_loc3='Ändere Spieleranzahl, Arenapunkte etc. für geladene Arenateams, sende geänderte Werte an die Spieler, die online sind...' WHERE entry=744;
UPDATE trinity_string SET content_loc3='Änderung abgeschlossen.' WHERE entry=745;
UPDATE trinity_string SET content_loc3='Abgleichen der Arenapunkte abgeschlossen.' WHERE entry=746;
UPDATE trinity_string SET content_loc3='Dieses Schlachtfeld ist gesperrt. Ihr könnte der Warteschlange nicht beitreten.' WHERE entry=747;
UPDATE trinity_string SET content_loc3='Arenakämpfe sind gesperrt. Ihr könnt der Warteschlange nicht beitreten.' WHERE entry=748;
UPDATE trinity_string SET content_loc3='Nicht genug Spieler. Das Spiel wird in %u Minuten geschlossen.' WHERE entry=750;
UPDATE trinity_string SET content_loc3='Nicht genug Spieler. Das Spiel wird in %u Sekunden geschlossen.' WHERE entry=751;
UPDATE trinity_string SET content_loc3='Die Schlacht der Kriegshymnenschlucht beginnt in 2 Minuten.' WHERE entry=753;
UPDATE trinity_string SET content_loc3='Die Schlacht des Arathibecken beginnt in 2 Minuten.' WHERE entry=754;
UPDATE trinity_string SET content_loc3='Der Kampf im Auge des Sturms beginnt in 2 Minuten.' WHERE entry=755;
UPDATE trinity_string SET content_loc3='Arena Prüfung auf %s geschaltet.' WHERE entry=785;
UPDATE trinity_string SET content_loc3='|cffff0000[Automatisch]:|r' WHERE entry=786;
UPDATE trinity_string SET content_loc3='|cffffff00[|c1f40af20Angekündigt von|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry=787;
UPDATE trinity_string SET content_loc3='ungültiger Name' WHERE entry=800;
UPDATE trinity_string SET content_loc3='Ihr habt nicht genügend Gold' WHERE entry=801;
UPDATE trinity_string SET content_loc3='Ihr habt nicht genügend freie Plätze' WHERE entry=802;
UPDATE trinity_string SET content_loc3='Eure Partner hat nicht genügend freie Taschenplätze' WHERE entry=803;
UPDATE trinity_string SET content_loc3='Ihr habt nicht die Berechtigung um diese Funktion auszuführen' WHERE entry=804;
UPDATE trinity_string SET content_loc3='Unbekannte Sprache' WHERE entry=805;
UPDATE trinity_string SET content_loc3='Ihr kennt diese Sprache nicht' WHERE entry=806;
UPDATE trinity_string SET content_loc3='Bitte gebt den Charakternamen an' WHERE entry=807;
UPDATE trinity_string SET content_loc3='Spieler %s nicht gefunden oder offline' WHERE entry=808;
UPDATE trinity_string SET content_loc3='Account für den Charakter %s nicht gefunden' WHERE entry=809;
UPDATE trinity_string SET content_loc3='|Hplayer:$N|h[$N]|h hat den Erfolg $a errungen!' WHERE entry=810;
UPDATE trinity_string SET content_loc3='Gildenmeister' WHERE entry=811;
UPDATE trinity_string SET content_loc3='Offizier' WHERE entry=812;
UPDATE trinity_string SET content_loc3='Veteran' WHERE entry=813;
UPDATE trinity_string SET content_loc3='Mitglied' WHERE entry=814;
UPDATE trinity_string SET content_loc3='Anfänger' WHERE entry=815;
UPDATE trinity_string SET content_loc3='Achtung: Ihr seid in eine Flugverbotszone eingedrungen und werdet demnächst zum Absteigen gezwungen werden.' WHERE entry=816;
UPDATE trinity_string SET content_loc3='Eintrag %u in der creature_template Datei nicht gefunden.' WHERE entry=817;
UPDATE trinity_string SET content_loc3='Eintrag %u in sCreatureStorage nicht gefunden. Möglicherweise ein neuer Eintrag in creature_template. Das Hinzufügen neuer NPCs erfordert einen Serverneustart.' WHERE entry=818;
UPDATE trinity_string SET content_loc3='Stadt' WHERE entry=819;
UPDATE trinity_string SET content_loc3='Beende daemon...' WHERE entry=1000;
UPDATE trinity_string SET content_loc3='Account wurde gelöscht: %s' WHERE entry=1001;
UPDATE trinity_string SET content_loc3='Account %s wurde NICHT gelöscht (SQL Dateiformat wurde warscheinlich aktualisiert)' WHERE entry=1002;
UPDATE trinity_string SET content_loc3='Account %s wurde NICHT gelöscht (unbekannter Fehler)' WHERE entry=1003;
UPDATE trinity_string SET content_loc3='Account erstellt: %s' WHERE entry=1004;
UPDATE trinity_string SET content_loc3='Account Name kann nicht länger als 16 Zeichen sein (Client Limit). Account wurde nicht erstellt!' WHERE entry=1005;
UPDATE trinity_string SET content_loc3='Es existiert bereits ein Account mit diesem Namen!' WHERE entry=1006;
UPDATE trinity_string SET content_loc3='Account %s wurde NICHT erstellt (SQL Dateiformat wurde warscheinlich aktualisiert)' WHERE entry=1007;
UPDATE trinity_string SET content_loc3='Account %s wurde NICHT erstellt (unbekannter Fehler)' WHERE entry=1008;
UPDATE trinity_string SET content_loc3='Spieler %s (Guid: %u) Account %s (Id: %u) wurde gelöscht.' WHERE entry=1009;
UPDATE trinity_string SET content_loc3='-[         Account][   Character][             IP][Map][Zone][Exp][GMLev]-' WHERE entry=1010;
UPDATE trinity_string SET content_loc3='|<Fehler>       | %20s |<Fehler>         |<Fe>| <Fehler>  |' WHERE entry=1011;
UPDATE trinity_string SET content_loc3='-==================================================================-' WHERE entry=1012;
UPDATE trinity_string SET content_loc3='-[%16s][%12s][%15s][%3d][%4d][%d][%d]-' WHERE entry=1013;
UPDATE trinity_string SET content_loc3='Keine Spieler online.' WHERE entry=1014;
UPDATE trinity_string SET content_loc3='-======================== Characters Online =======================-' WHERE entry=1015;
UPDATE trinity_string SET content_loc3='| GUID       | Name                 | Account                      | gelöscht am         |' WHERE entry=1016;
UPDATE trinity_string SET content_loc3='| %10u | %20s | %15s (%10u) | %19s |' WHERE entry=1017;
UPDATE trinity_string SET content_loc3='==========================================================================================' WHERE entry=1018;
UPDATE trinity_string SET content_loc3='Keine Charactere gefunden' WHERE entry=1019;
UPDATE trinity_string SET content_loc3='Die folgenden Charactere werden wiederhergestellt.' WHERE entry=1020;
UPDATE trinity_string SET content_loc3='Die folgenden Charactere werden gelöscht.' WHERE entry=1021;
UPDATE trinity_string SET content_loc3='FEHLER: Ein neuer Name kann nur vergeben werden, wenn nur ein Character ausgewählt wurde!' WHERE entry=1022;
UPDATE trinity_string SET content_loc3='Character \'%s\' (GUID: %u Account %u) kann nicht wiederhergestellt werden. Der Account existiert nicht!' WHERE entry=1023;
UPDATE trinity_string SET content_loc3='Character \'%s\' (GUID: %u Account %u) kann nicht wiederhergestellt werden. Die Character-Liste des Accounts ist voll!' WHERE entry=1024;
UPDATE trinity_string SET content_loc3='Character \'%s\' (GUID: %u Account %u) kann nicht wiederhergestellt werden. Der neue Name wird bereits verwendet!' WHERE entry=1025;
UPDATE trinity_string SET content_loc3='GUID: %u Name: %s Account: %s (%u) Datum: %s' WHERE entry=1026;
UPDATE trinity_string SET content_loc3='SQL query log eingeschaltet.' WHERE entry=1027;
UPDATE trinity_string SET content_loc3='SQL query log abgeschaltet.' WHERE entry=1028;

UPDATE trinity_string SET content_loc3='Dem Account %s (Id: %u) sind jetzt die Erweiterungen bis %u zugelassen.' WHERE entry=1100;
UPDATE trinity_string SET content_loc3='Nachricht des Tages wurde geändert zu:\r\n%s' WHERE entry=1101;
UPDATE trinity_string SET content_loc3='Nachricht geschickt an %s: %s' WHERE entry=1102;
UPDATE trinity_string SET content_loc3='%d - %s %s' WHERE entry=1103;
UPDATE trinity_string SET content_loc3='%d - %s' WHERE entry=1104;
UPDATE trinity_string SET content_loc3='%d - %s' WHERE entry=1105;
UPDATE trinity_string SET content_loc3='%d - %s %s' WHERE entry=1106;
UPDATE trinity_string SET content_loc3='%d - %s' WHERE entry=1107;
UPDATE trinity_string SET content_loc3='%d - %s %s' WHERE entry=1108;
UPDATE trinity_string SET content_loc3='%d - %s %s %s %s' WHERE entry=1109;
UPDATE trinity_string SET content_loc3='%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1110;
UPDATE trinity_string SET content_loc3='%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry=1111;
UPDATE trinity_string SET content_loc3='Öffnen folgender Datei fehlgeschlagen: %s' WHERE entry=1112;
UPDATE trinity_string SET content_loc3='Account %s (%u) hat die maximal erlaubt Anzahl Charaktere (Client Limit)' WHERE entry=1113;
UPDATE trinity_string SET content_loc3='Dump file enthält fehlerhafte Daten!' WHERE entry=1114;
UPDATE trinity_string SET content_loc3='Ungültiger Charakter Name!' WHERE entry=1115;
UPDATE trinity_string SET content_loc3='Ungültige  Charakter Guid!' WHERE entry=1116;
UPDATE trinity_string SET content_loc3='Charakter Guid %u wird bereits verwendet!' WHERE entry=1117;
UPDATE trinity_string SET content_loc3='%d - Gilde: %s (Guid: %u) %s' WHERE entry=1118;
UPDATE trinity_string SET content_loc3='Ihr müsst "male" (männlich) oder "female" (weiblich) als Geschlecht benutzen.' WHERE entry=1119;
UPDATE trinity_string SET content_loc3='Ihr verändert das Geschlecht von %s auf %s.' WHERE entry=1120;
UPDATE trinity_string SET content_loc3='Euer Geschlecht wurde auf %s von %s geändert.' WHERE entry=1121;
UPDATE trinity_string SET content_loc3='(%u/%u +perm %u +temp %u)' WHERE entry=1122;
UPDATE trinity_string SET content_loc3='Kein Tier gefunden' WHERE entry=1123;
UPDATE trinity_string SET content_loc3='Falsche Tierart' WHERE entry=1124;
UPDATE trinity_string SET content_loc3='Euer Tier hat alle Talente erlernt.' WHERE entry=1125;
UPDATE trinity_string SET content_loc3='Die Talente von deinem Tier wurden zurückgesetzt.' WHERE entry=1126;
UPDATE trinity_string SET content_loc3='Talente von %s\'s Tier wurden zurückgesetzt.' WHERE entry=1127;
UPDATE trinity_string SET content_loc3='%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1128;
UPDATE trinity_string SET content_loc3='%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1129;
UPDATE trinity_string SET content_loc3='Abbruch: Gelöschte Chars können nicht gedumpt werden.' WHERE entry=1130;
UPDATE trinity_string SET content_loc3='Die folgenden Chars entsprechen eurer Suchanfrage.' WHERE entry=1131;
UPDATE trinity_string SET content_loc3='Zur Zeit gebannte Chars:' WHERE entry=1132;
UPDATE trinity_string SET content_loc3='|   Character   |   Ban Datum  |  Unban Datum |  gebannt von  |   Ban Grund   |' WHERE entry=1133;
UPDATE trinity_string SET content_loc3='Das Senden von Tickets ist erlaubt.' WHERE entry=1134;
UPDATE trinity_string SET content_loc3='Das Senden von Tickets ist verboten.' WHERE entry=1135;
UPDATE trinity_string SET content_loc3='Der Charakter %s wurde noch nie gebannt!' WHERE entry=1136;
UPDATE trinity_string SET content_loc3='Der Dev mode ist an (ON)!' WHERE entry=1137;
UPDATE trinity_string SET content_loc3='Der Dev mode ist aus (OFF)!' WHERE entry=1138;
UPDATE trinity_string SET content_loc3='Folge dem Spieler %s (lowguid %u)' WHERE entry=1139;
UPDATE trinity_string SET content_loc3='Folge dem NPC %s (lowguid %u)' WHERE entry=1140;
UPDATE trinity_string SET content_loc3='Folge <NULL>' WHERE entry=1141;
UPDATE trinity_string SET content_loc3='Effect movement' WHERE entry=1142;
UPDATE trinity_string SET content_loc3='aktuelle Bewegungsflags (moveFlags) des Zieles: %u, moveFlagsExtra: %u.' WHERE entry=1143;
UPDATE trinity_string SET content_loc3='Bewegungsflags (moveFlgas) auf %u, moveFlagsExtra auf %u geändert.' WHERE entry=1144;

UPDATE trinity_string SET content_loc3='Ihr versucht den Film %u anzusehen, dieser existiert jedoch nicht.' WHERE entry=1200;
UPDATE trinity_string SET content_loc3='Ihr versucht den Film %u anzusehen, dieser existiert jedoch nicht.' WHERE entry=1201;
UPDATE trinity_string SET content_loc3='Areatrigger debugging eingeschaltet.' WHERE entry=1202;
UPDATE trinity_string SET content_loc3='Areatrigger debugging abgeschaltet.' WHERE entry=1203;
UPDATE trinity_string SET content_loc3='Ihr seid bei Areatrigger %u.' WHERE entry=1204;

#(1205,'The battle will begin in two minutes.'),
#(1206,'The battle will begin in 1 minute.'),
#(1208,'The battle has begun!'),
#(1207,'The battle will begin in 30 seconds!'),
#(1209,'the alliance keep'),
#(1210,'the horde keep'),
#(1211,'%s wins!'),
#(1212,'The west gate of %s is destroyed!'),
#(1213,'The east gate of %s is destroyed!'),
#(1214,'The south gate of %s is destroyed!'),
#(1215,'The north gate of %s is destroyed!'),
#(1216,'$n has assaulted the %s'),
#(1217,'$n has defended the %s'),
#(1218,'$n claims the %s! If left unchallenged, the %s will control it in 1 minute!'),
#(1219,'The %s has taken the %s'),
#(1220,'Workshop'),
#(1221,'Docks'),
#(1222,'Refinery'),
#(1223,'Quarry'),
#(1224,'Hangar');

UPDATE trinity_string SET content_loc3='Allianz' WHERE entry=1300;
UPDATE trinity_string SET content_loc3='Horde' WHERE entry=1301;
UPDATE trinity_string SET content_loc3='%s wurde von der %s zerstört!' WHERE entry=1302;
UPDATE trinity_string SET content_loc3='%s wird angegriffen! Wenn er unbewacht bleibt, wird die %s ihn zerstören!' WHERE entry=1303;
UPDATE trinity_string SET content_loc3='%s wurde von der %s erobert!' WHERE entry=1304;
UPDATE trinity_string SET content_loc3='%s wurde von der %s erobert!' WHERE entry=1305;
UPDATE trinity_string SET content_loc3='%s wurde von der %s erobert!' WHERE entry=1306;
UPDATE trinity_string SET content_loc3='%s wird angegriffen! Wenn er unbewacht bleibt, wird die %s ihn erobern!' WHERE entry=1307;
UPDATE trinity_string SET content_loc3='Die %s hat die %s eingenommen! Die dort befindlichen Vorräte werden zur Verstärkung eingesetzt!' WHERE entry=1308;
UPDATE trinity_string SET content_loc3='Eisenschachtmine' WHERE entry=1309;
UPDATE trinity_string SET content_loc3='Eisbeißermine' WHERE entry=1310;
UPDATE trinity_string SET content_loc3='Das Lazarett der Sturmlanzen' WHERE entry=1311;
UPDATE trinity_string SET content_loc3='Der Südbunker von Dun Baldar' WHERE entry=1312;
UPDATE trinity_string SET content_loc3='Der Nordbunker von Dun Baldar' WHERE entry=1313;
UPDATE trinity_string SET content_loc3='Friedhof der Sturmlanzen' WHERE entry=1314;
UPDATE trinity_string SET content_loc3='Der Eisschwingenbunker' WHERE entry=1315;
UPDATE trinity_string SET content_loc3='Der Steinbruchfriedhof' WHERE entry=1316;
UPDATE trinity_string SET content_loc3='Der Steinbruchbunker' WHERE entry=1317;
UPDATE trinity_string SET content_loc3='Der Schneewehenfriedhof' WHERE entry=1318;
UPDATE trinity_string SET content_loc3='Der Eisblutturm' WHERE entry=1319;
UPDATE trinity_string SET content_loc3='Der Eisblutfriedhof' WHERE entry=1320;
UPDATE trinity_string SET content_loc3='Die Turmstellung' WHERE entry=1321;
UPDATE trinity_string SET content_loc3='Der Friedhof der Frostwölfe' WHERE entry=1322;
UPDATE trinity_string SET content_loc3='Der östliche Frostwolfturm' WHERE entry=1323;
UPDATE trinity_string SET content_loc3='Der westliche Frostwolfturm' WHERE entry=1324;
UPDATE trinity_string SET content_loc3='Die Heilerhütte der Frostwölfe' WHERE entry=1325;
UPDATE trinity_string SET content_loc3='Der Kampf um das Alteractal beginnt in 1 Minute.' WHERE entry=1326;
UPDATE trinity_string SET content_loc3='Der Kampf um das Alteractal beginnt in 30 Sekunden.' WHERE entry=1327;
UPDATE trinity_string SET content_loc3='Der Kampf um das Alteractal hat begonnen!' WHERE entry=1328;
UPDATE trinity_string SET content_loc3='Die Allianz hat nurnoch wenige Verstärkungspunkte' WHERE entry=1329;
UPDATE trinity_string SET content_loc3='Die Horde hat nurnoch wenige Verstärkungspunkte' WHERE entry=1330;
UPDATE trinity_string SET content_loc3='Der General der Frostwölfe ist tot!' WHERE entry=1331;
UPDATE trinity_string SET content_loc3='Der General der Sturmlanzen ist tot!' WHERE entry=1332;
UPDATE trinity_string SET content_loc3='Der Kampf um das Alteractal beginnt in 2 Minuten.' WHERE entry=1333;

UPDATE trinity_string SET content_loc3='|cff00ff00Neues Ticket von|r|cffff00ff %s.|r |cff00ff00Ticket entry:|r|cffff00ff %d.|r' WHERE entry=2000;
UPDATE trinity_string SET content_loc3='|cff00ff00Charakter|r|cffff00ff %s |r|cff00ff00bearbeite ihr/sein Ticket:|r|cffff00ff %d.|r' WHERE entry=2001;
UPDATE trinity_string SET content_loc3='|cff00ff00Charakter|r|cffff00ff %s |r|cff00ff00aufgegebene Ticket entry:|r|cffff00ff %d.|r' WHERE entry=2002;
UPDATE trinity_string SET content_loc3='|cff00ff00Geschlossen von|r:|cff00ccff %s|r ' WHERE entry=2003;
UPDATE trinity_string SET content_loc3='|cff00ff00Gelöscht von|r:|cff00ccff %s|r ' WHERE entry=2004;
UPDATE trinity_string SET content_loc3='Ticket nicht gefunden.' WHERE entry=2005;
UPDATE trinity_string SET content_loc3='Bitte Ticket erst schließen. Bevor es endgültig gelöscht wird.' WHERE entry=2006;
UPDATE trinity_string SET content_loc3='Ticket %d ist bereits zugeordnet.' WHERE entry=2007;
UPDATE trinity_string SET content_loc3='%u Tickets erfolgreich neu geladen.' WHERE entry=2008;
UPDATE trinity_string SET content_loc3='Zeige die Liste der offenen Tickets an.' WHERE entry=2009;
UPDATE trinity_string SET content_loc3='Zeige die Liste der offenen Tickets an, deren Autor online ist, an.' WHERE entry=2010;
UPDATE trinity_string SET content_loc3='Zeige die Liste der geschlossenen Tickets an.' WHERE entry=2011;
UPDATE trinity_string SET content_loc3='Ungültiger Name. Der Name sollte von einem Gamemaster sein der online ist.' WHERE entry=2012;
UPDATE trinity_string SET content_loc3='Dieses Ticket ist euch bereits zugeordnet. Um es neu zuzuweisen verwendet ".ticket unassign %d" und ordnet es neu zu.' WHERE entry=2013;
UPDATE trinity_string SET content_loc3='Ticket %d ist nicht zugewiesen. Ihr könnt keine Zuweisung löschen.' WHERE entry=2014;
UPDATE trinity_string SET content_loc3='Ihr könnt keine Ticket-Zuordnung zu einem Teammitglieder das ein höheres Sicherheitslevel als ihr hat auflösen.' WHERE entry=2015;
UPDATE trinity_string SET content_loc3='Kann das Ticket %d nicht schließen. Es ist einem anderen GM zugeordnet.' WHERE entry=2016;
UPDATE trinity_string SET content_loc3='|cffaaffaaTicket|r:|cffaaccff %d.|r ' WHERE entry=2017;
UPDATE trinity_string SET content_loc3='|cff00ff00Erstellt von|r:|cff00ccff %s|r ' WHERE entry=2018;
UPDATE trinity_string SET content_loc3='|cff00ff00letzte Änderung|r:|cff00ccff vor %s|r ' WHERE entry=2019;
UPDATE trinity_string SET content_loc3='|cff00ff00Zugewiesen zu|r:|cff00ccff %s|r ' WHERE entry=2020;
UPDATE trinity_string SET content_loc3='|cff00ff00Zuordnung aufgelöst von|r:|cff00ccff %s|r ' WHERE entry=2021;
UPDATE trinity_string SET content_loc3='|cff00ff00Nachricht|r: [%s]|r ' WHERE entry=2022;
UPDATE trinity_string SET content_loc3='|cff00ff00GM-Kommentar|r: [%s]|r ' WHERE entry=2023;
UPDATE trinity_string SET content_loc3='|cff00ccff%s|r |cff00ff00Kommentar hinzugefügt|r: [%s]|r ' WHERE entry=2024;
UPDATE trinity_string SET content_loc3='|cff00ff00Erzeugt|r:|cff00ccff vor %s|r ' WHERE entry=2025;
UPDATE trinity_string SET content_loc3='Es sind noch Tickets offen. Bitte schließt diese zuerst!' WHERE entry=2027;
UPDATE trinity_string SET content_loc3='Alle geschlossenen Tickets wurden gelöscht und der Ticketzähler auf |cffff00ff 1|r zurückgesetzt.' WHERE entry=2028;

UPDATE trinity_string SET content_loc3='Ihr habt Spieler %s eingefroren' WHERE entry=5000;
UPDATE trinity_string SET content_loc3='Das könnte zwar recht lustig werden, aber nein... ihr könnt euch nicht selbst einfrieren!' WHERE entry=5001;
UPDATE trinity_string SET content_loc3='Falsche Eingabe! Überprüfe den Namen des Ziels.' WHERE entry=5002;
UPDATE trinity_string SET content_loc3='Spieler %s ist nicht mehr eingefroren.' WHERE entry=5003;
UPDATE trinity_string SET content_loc3='Zur Zeit sind keine Spieler eingefroren.' WHERE entry=5004;
UPDATE trinity_string SET content_loc3='Folgende Spieler sind zur Zeit auf dem Server eingefroren:' WHERE entry=5005;
UPDATE trinity_string SET content_loc3='- %s' WHERE entry=5006;
UPDATE trinity_string SET content_loc3='Ihr müsst einem Schlachtzug angehören, um diese Instanz zu betreten.' WHERE entry=5007;
UPDATE trinity_string SET content_loc3='Diese Instanz ist geschlossen.' WHERE entry=5008;
UPDATE trinity_string SET content_loc3='Sound %u wird für den ganzen Server abgespielt.' WHERE entry=5009;
UPDATE trinity_string SET content_loc3='linkGUID: %u, Entry: %u (%s)' WHERE entry=5010;
UPDATE trinity_string SET content_loc3='Ihr könnt euch nicht zu euch selbst teleportieren.' WHERE entry=5011;
UPDATE trinity_string SET content_loc3='Keine Karten gefunden.' WHERE entry=5012;
UPDATE trinity_string SET content_loc3='[Kontinent]' WHERE entry=5013;
UPDATE trinity_string SET content_loc3='[Instanz]' WHERE entry=5014;
UPDATE trinity_string SET content_loc3='[Schlachtfeld]' WHERE entry=5015;
UPDATE trinity_string SET content_loc3='[Arena]' WHERE entry=5016;
UPDATE trinity_string SET content_loc3='[Raid reset Zeit: %s]' WHERE entry=5017;
UPDATE trinity_string SET content_loc3='[Heroisch reset Zeit: %s]' WHERE entry=5018;
UPDATE trinity_string SET content_loc3='[Reitbar]' WHERE entry=5019;
UPDATE trinity_string SET content_loc3='Phasemask: %u' WHERE entry=5020;
UPDATE trinity_string SET content_loc3='Rüstung: %u' WHERE entry=5021;
UPDATE trinity_string SET content_loc3='Channelbesitz an die Person übertragen, die als erster dem Channel beitritt: aktiv' WHERE entry=5022;
UPDATE trinity_string SET content_loc3='Channelbesitz an die Person übertragen, die als erster dem Channel beitritt: inaktiv' WHERE entry=5023;
UPDATE trinity_string SET content_loc3='Entry: %u' WHERE entry=5024;
UPDATE trinity_string SET content_loc3='Type: %u' WHERE entry=5025;
UPDATE trinity_string SET content_loc3='DisplayID: %u' WHERE entry=5026;
UPDATE trinity_string SET content_loc3='Name: %s' WHERE entry=5027;
UPDATE trinity_string SET content_loc3='Lootid: %u' WHERE entry=5028;
UPDATE trinity_string SET content_loc3='Zu viele Ergebnisse. (max: %d Ergebnisse)' WHERE entry=5029;
UPDATE trinity_string SET content_loc3='%s versucht vor Angst davon zu rennen!' WHERE entry=5030;
UPDATE trinity_string SET content_loc3='AIName: %s ScriptName: %s' WHERE entry=5031;

UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %d sein, bevor Ihr sprechen, rufen oder emotes nutzen dürft.' WHERE entry=6604;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %d sein, bevor Ihr flüstern dürft.' WHERE entry=6605;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %d sein, bevor Ihr in Channels schreiben dürft.' WHERE entry=6606;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %d sein, bevor Ihr das Auktionshaus nutzen dürft.' WHERE entry=6607;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %d sein, bevor Ihr Tickets schreiben dürft.' WHERE entry=6608;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %d sein, bevor Ihr handeln dürft.' WHERE entry=6609;
UPDATE trinity_string SET content_loc3='Der Handel mit Spielern unter Level %d ist nicht möglich.' WHERE entry=6610;
UPDATE trinity_string SET content_loc3='Ihr müsst mindestens Level %d sein, bevor Ihr Post senden dürft.' WHERE entry=6611;
UPDATE trinity_string SET content_loc3='Das Senden von Post an Spielern unter Level %d ist nicht möglich.' WHERE entry=6612;
UPDATE trinity_string SET content_loc3='|cfff00000[GM Ankündigung von [%s]]: %s|r' WHERE entry=6613;
UPDATE trinity_string SET content_loc3='Mitteilung an GM\'s - ' WHERE entry=6614;
UPDATE trinity_string SET content_loc3='|cffffff00[|c1f40af20GM Ankündigung von|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry=6615;
UPDATE trinity_string SET content_loc3='Ruhe ist AN für %s' WHERE entry=6616;
UPDATE trinity_string SET content_loc3='Welt: Verweigere Verbindungen' WHERE entry=7523;
UPDATE trinity_string SET content_loc3='Welt: Akzeptiere Verbindungen' WHERE entry=7524;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Rundblick übernommen!' WHERE entry=10001;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Rundblick übernommen!' WHERE entry=10002;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über das Stadium übernommen!' WHERE entry=10003;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über das Stadium übernommen!' WHERE entry=10004;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Trümmerbastion übernommen!' WHERE entry=10005;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Trümmerbastion übernommen!' WHERE entry=10006;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Rundblick verloren!' WHERE entry=10007;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Rundblick verloren!' WHERE entry=10008;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über das Stadium verloren!' WHERE entry=10009;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über das Stadium verloren!' WHERE entry=10010;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Trümmerbastion verloren!' WHERE entry=10011;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Trümmerbastion verloren!' WHERE entry=10012;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über das westliche Leuchtsignal übernommen!' WHERE entry=10013;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über das westliche Leuchtsignal übernommen!' WHERE entry=10014;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über das östliche Leuchtsignal übernommen!' WHERE entry=10015;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über das östliche Leuchtsignal übernommen!' WHERE entry=10016;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Ruinen der Zwillingsspitze übernommen!' WHERE entry=10017;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Ruinen der Zwillingsspitze übernommen!' WHERE entry=10018;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über das westliche Leuchtsignal verloren!' WHERE entry=10019;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über das westliche Leuchtsignal verloren!' WHERE entry=10020;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über das östliche Leuchtsignal verloren!' WHERE entry=10021;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über das östliche Leuchtsignal verloren!' WHERE entry=10022;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über die Ruinen der Zwillingsspitze verloren!' WHERE entry=10023;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über die Ruinen der Zwillingsspitze verloren!' WHERE entry=10024;
UPDATE trinity_string SET content_loc3='Die Horde hat Halaa erobert!' WHERE entry=10025;
UPDATE trinity_string SET content_loc3='Die Allianz hat Halaa erobert!' WHERE entry=10026;
UPDATE trinity_string SET content_loc3='Die Horde hat Halaa verloren!' WHERE entry=10027;
UPDATE trinity_string SET content_loc3='Die Allianz hat Halaa verloren!' WHERE entry=10028;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über einen Geisterturm übernommen!' WHERE entry=10029;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über einen Geisterturm übernommen!' WHERE entry=10030;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über einen Geisterturm verloren!' WHERE entry=10031;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über einen Geisterturm verloren!' WHERE entry=10032;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Nordpassturm übernommen!' WHERE entry=10033;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Nordpassturm übernommen!' WHERE entry=10034;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Ostwallturm übernommen!' WHERE entry=10035;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Ostwallturm übernommen!' WHERE entry=10036;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Turm der Kronwache übernommen!' WHERE entry=10037;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Turm der Kronwache übernommen!' WHERE entry=10038;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Pestwaldturm übernommen!' WHERE entry=10039;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Pestwaldturm übernommen!' WHERE entry=10040;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Nordpassturm verloren!' WHERE entry=10041;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Nordpassturm verloren!' WHERE entry=10042;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Ostwallturm verloren!' WHERE entry=10043;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Ostwallturm verloren!' WHERE entry=10044;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Turm der Kronwache verloren!' WHERE entry=10045;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Turm der Kronwache verloren!' WHERE entry=10046;
UPDATE trinity_string SET content_loc3='Die Horde hat die Kontrolle über den Pestwaldturm verloren!' WHERE entry=10047;
UPDATE trinity_string SET content_loc3='Die Allianz hat die Kontrolle über den Pestwaldturm verloren!' WHERE entry=10048;
UPDATE trinity_string SET content_loc3='Die Horde hat 200 Silithyst eingesammelt!' WHERE entry=10049; /* Silithyst(s) ?! Should be verified */
UPDATE trinity_string SET content_loc3='Die Allianz hat 200 Silithyst eingesammelt!' WHERE entry=10050; /* Silithyst(s) ?! Should be verified */
UPDATE trinity_string SET content_loc3='Bringt mich zum Nordpassturm.' WHERE entry=10051;
UPDATE trinity_string SET content_loc3='Bringt mich zum Ostwallturm.' WHERE entry=10052;
UPDATE trinity_string SET content_loc3='Bringt mich zum Turm der Kronwache.' WHERE entry=10053;
UPDATE trinity_string SET content_loc3='Gebt mir die Flagge, ich werde sie zum zentralen Leuchtsignal bringen. Zum Ruhm der Allianz!' WHERE entry=10054;
UPDATE trinity_string SET content_loc3='Gebt mir die Flagge, ich werde sie zum zentralen Leuchtsignal bringen. Zum Ruhm der Horde!' WHERE entry=10055;
UPDATE trinity_string SET content_loc3='Die Schlacht um den Strand der Uralten beginnt in 2 Minuten.' WHERE entry=10056;
UPDATE trinity_string SET content_loc3='Die Schlacht um den Strand der Uralten beginnt in 1 Minute.' WHERE entry=10057;
UPDATE trinity_string SET content_loc3='Die Schlacht um den Strand der Uralten beginnt in 30 Sekunden. Bereitet Euch vor!' WHERE entry=10058;
UPDATE trinity_string SET content_loc3='Lasst die Schlacht um den Strand der Uralten beginnen!' WHERE entry=10059;
UPDATE trinity_string SET content_loc3='%s wird angegriffen!' WHERE entry=10060;
UPDATE trinity_string SET content_loc3='%s wurde zerstört!' WHERE entry=10061;
UPDATE trinity_string SET content_loc3='Runde 1 -  beendet.' WHERE entry=10062;
UPDATE trinity_string SET content_loc3='Die Allianz hat das Titanen Portal erobert.' WHERE entry=10063;
UPDATE trinity_string SET content_loc3='Die Horde hat das Titanen Portal erobert.' WHERE entry=10064;
UPDATE trinity_string SET content_loc3='Runde 2 der Schlacht um den Strand der Uralten beginnt in 1 Minute.' WHERE entry=10065;
UPDATE trinity_string SET content_loc3='Runde 2 der Schlacht um den Strand der Uralten beginnt in 30 Sekunden. Bereitet Euch vor!' WHERE entry=10066;
UPDATE trinity_string SET content_loc3='Die Kammer ist aufgebrochen! Das Relikt der Titanen ist verwundbar!' WHERE entry=10067;
UPDATE trinity_string SET content_loc3='Die Allianz hat den südlichen Friedhof erobert.' WHERE entry=10068;
UPDATE trinity_string SET content_loc3='Die Allianz hat den westlichen Friedhof erobert.' WHERE entry=10069;
UPDATE trinity_string SET content_loc3='Die Allianz hat den östlichen Friedhof erobert.' WHERE entry=10070;
UPDATE trinity_string SET content_loc3='Die Horde hat den südlichen Friedhof erobert.' WHERE entry=10071;
UPDATE trinity_string SET content_loc3='Die Horde hat den westlichen Friedhof erobert.' WHERE entry=10072;
UPDATE trinity_string SET content_loc3='Die Horde hat den östlichen Friedhof erobert.' WHERE entry=10073;
UPDATE trinity_string SET content_loc3='|cffffff00[|c00077766Autobroadcast|cffffff00]: |cFFF222FF%s|r' WHERE entry=11000;
UPDATE trinity_string SET content_loc3='Ihr habt nicht -1 oder die aktuelle realmId eures Realms angegeben.' WHERE entry=11001;

SET NAMES 'latin1';
