ALTER TABLE `logs`
 CHANGE `time` `time` INT(10) UNSIGNED NOT NULL,
 CHANGE `realm` `realm` INT(10) UNSIGNED NOT NULL,
 CHANGE `type` `type` TINYINT(3) UNSIGNED NOT NULL,
 ROW_FORMAT=DEFAULT ENGINE=INNODB;
ALTER TABLE `realmcharacters`
 CHANGE `realmid` `realmid` INT(10) UNSIGNED DEFAULT 0 NOT NULL,
 CHANGE `acctid` `acctid` INT(10) UNSIGNED NOT NULL,
 ROW_FORMAT=DEFAULT ENGINE=INNODB;
ALTER TABLE `realmlist`
 CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 CHANGE `address` `address` VARCHAR(15) DEFAULT '127.0.0.1' NOT NULL,
 CHANGE `port` `port` SMALLINT(5) UNSIGNED DEFAULT '8085' NOT NULL,
 CHANGE `gamebuild` `gamebuild` INT(10) UNSIGNED DEFAULT '12340' NOT NULL,
 ROW_FORMAT=DEFAULT ENGINE=INNODB;
ALTER TABLE `uptime`
 DROP COLUMN `startstring`,
 CHANGE `realmid` `realmid` INT(10) UNSIGNED NOT NULL,
 CHANGE `starttime` `starttime` INT(10) UNSIGNED DEFAULT 0 NOT NULL,
 CHANGE `uptime` `uptime` INT(10) UNSIGNED DEFAULT 0 NOT NULL,
 ROW_FORMAT=DEFAULT ENGINE=INNODB;
ALTER TABLE `realmlist` CHANGE `address` `address` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '127.0.0.1';
ALTER TABLE `realmlist` CHANGE `address` `address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '127.0.0.1';
